Andrew updated violin plots
LLNL/thicket pull request #110
Opened 2023-11-02 21:22 UTC by AndyM1098

Created two functions in order to plot violin plots.

The first function is designed to take in a singular thicket object, and plot user defined nodes and columns. The x-axis would be each node, and the y-axis would be the column metric specified by the user

The second function is designed to take in more than one thicket object, were we plot a node for each thicket, and the y-axis would be the data for each node. There are a few key things that are enforced. First, all thickets passed in needs to have the same columnar index level. Each thicket only gets one node to plot.

Both functions support custom percentile lines that would be user defined, as well as line styles and line colors.

2023-11-06 21:34 UTC, AndyM1098 commented on thicket/stats/display_violinplot.py
> +                # Plot line
Add link to plotting line reference

2023-11-06 21:35 UTC, AndyM1098 commented on thicket/stats/display_violinplot.py
> +                    column in thicket.exc_metrics
Change to check if column is in the actual statsframe, and not the list of metrics

2023-11-06 22:21 UTC, ilumsden requested changes
Looks pretty good to start. There are definitely still some things we need to work through as a group for `display_violinplot_thicket`

2023-11-06 22:21 UTC, ilumsden commented on thicket/stats/display_violinplot.py
> +    percentile_colors=[],
Change the accepted values of `percentiles`, `percentile_linestyles`, and `percentile_colors` as follows:

`percentiles` can be one of three values:
1. `None` = don't plot percentile lines
2. A single `float` = plot a single percentile line
3. A list of `float` = plot multiple percentile lines

`percentile_linestyle` and `percentile_colors` can be one of the following:
1. `None` = use default linestyles or colors
2. A single valid value for MPL's `linestyle` or `color` parameters = use the specified linestyle or color for every percentile line
3. A list of valid values for MPL's `linestyle` or `color` = use the specified linestyles of color for each percentile line. There needs to be a size check in this case to ensure the length of the list equals the length of the `percentiles` list

2023-11-06 22:21 UTC, ilumsden commented on thicket/stats/display_violinplot.py
> +                ):
Replace this with a check on the `dataframe` columns instead of `exc_metrics` and `inc_metrics`

2023-11-06 22:21 UTC, ilumsden commented on thicket/stats/display_violinplot.py
> +                # Plot line
Add a short comment that includes the link to StackOverflow where we found the code to do this

2023-11-06 22:21 UTC, ilumsden commented on thicket/stats/display_violinplot.py
> +            return sns.violinplot(data=filtered_df, x="node", y=" ", **kwargs)
Restructure all of this to minimize code duplication. For example, you could use something like the following psuedo code
```
graph = None
if len(columns) > 1:
    graph = <code to plot columnar join>
else:
    graph = <code to plot non-columnar join>
if len(percentiles) != 0:
    return <code to add percentile lines>
return graph
```

2023-11-06 22:21 UTC, ilumsden commented on thicket/stats/display_violinplot.py
> +    percentile_colors=[],
See the comment above about `percentiles`, `percentile_linestyles`, and `percentile_colors`

2023-11-06 22:21 UTC, ilumsden commented on thicket/stats/display_violinplot.py
> +    x_order=None,
We still need to decide whether it makes more sense for `thickets`, `nodes`, and `columns` to be dictionaries or lists.

Additionally, we could consider letting `nodes` be a value that we use internally to get the actual Hatchet `Node` objects we need. For example, we could let `nodes` be a string representing the name of a node. Or, we could let it be a `Callable` that we invoke to get the `Node` object.

2023-11-06 22:21 UTC, ilumsden commented on thicket/stats/display_violinplot.py
> +        lines_styles += ["--"] * (len(percentiles_vals) - len(lines_styles))
Change this based on the comments regarding `percentiles`, `percentile_linestyles`, and `percentile_colors`

2023-11-06 22:21 UTC, ilumsden commented on thicket/stats/display_violinplot.py
> +        )
Move the code that builds the `position` list and the code that creates `filtered_df` outside of this if-else to avoid excessive code duplication

2023-11-06 22:21 UTC, ilumsden commented on thicket/stats/display_violinplot.py
> +        line_colors += ["black"] * (len(percentiles_vals) - len(line_colors))
See comment for this same section in the other percentile line plotting function

2023-11-06 22:21 UTC, ilumsden commented on thicket/stats/display_violinplot.py
> +                added_line.set_clip_path(patch)
Could the interior of this large for loop be abstracted into another internal function? That would avoid the large amounts of code duplication in this function and `_add_percentile_lines_node`.

2023-11-06 22:21 UTC, ilumsden commented on thicket/stats/display_violinplot.py
> +    **kwargs,
@slabasan could it be useful to utilize type hints here? This is a feature since Python 3.5. If we were to use it, the function signature would look something like this:

```python3
import typing

def display_violinplot_thicket(
    thickets: dict[typing.Any, thicket.Thicket], # using 'Any' since we don't have a predefined type for groupby keys
    nodes: dict[typing.Any, hatchet.node.Node],
    columns: dict[typing.Any, list[str]],
    x_order=None, # x_order is the first optional argument
    ...):
    ...
```

2023-11-06 22:21 UTC, ilumsden commented on thicket/stats/display_violinplot.py
> +        raise ValueError("Columns dictionary must have list of columns as values")
A lot of these type checks can be removed if we decide to use type hinting

2023-11-06 22:21 UTC, ilumsden commented on thicket/stats/display_violinplot.py
> +            filtered_dfs[thicket_idx]["node"] = thicket_name
Could some of this code be abstracted into a separate internal function that can be used by both `display_violinplot` functions?

2023-11-06 22:21 UTC, ilumsden commented on thicket/stats/display_violinplot.py
> +            return sns.violinplot(data=filtered_df, x="node", y=" ", **kwargs)
Actually, just replicate what you did in `display_violinplot_thicket`. That's what I'm suggesting here.

2023-11-07 17:17 UTC, AndyM1098 commented on thicket/stats/display_violinplot.py
> +        raise ValueError("Columns dictionary must have list of columns as values")
Make sure type hinting throws an error on wrong types being passed in

2023-11-07 17:18 UTC, AndyM1098 commented
Get rid of new lines below statements like if else, and for loops

2024-03-04 22:17 UTC, slabasan commented
All changes moved to #127

2024-03-04 22:17 UTC, closed without merging