WIP add examples directory and initial docs
LLNL/thicket pull request #153
Opened 2024-04-23 17:42 UTC by slabasan

- remove examples/python_scripts/.gitignore once a python file has been added

2024-05-13 17:07 UTC, michaelmckinsey1 commented on examples/python_scripts/stacked_line_graphs.py
> +sys.path.append("/g/g20/hao3/thicket")
change this to `sys.path.append("/usr/gapps/spot/dev/thicket-playground-dev/")`

2024-05-13 17:07 UTC, michaelmckinsey1 commented on examples/python_scripts/stacked_line_graphs.py
> +import argparse
For Thicket, we follow PEP 8, so all imports should follow [these requirements](https://peps.python.org/pep-0008/#:~:text=Imports%20are%20always,group%20of%20imports.).

```
Imports are always put at the top of the file, just after any module comments and docstrings, and before module globals and constants.
Imports should be grouped in the following order:

1. Standard library imports.
2. Related third party imports.
3. Local application/library specific imports.

You should put a blank line between each group of imports.
```

2024-05-13 17:26 UTC, michaelmckinsey1 commented on examples/python_scripts/stacked_line_graphs.py
> +    grouped_ctk = ctk.dataframe.groupby("name").sum()
The result of `ctk.dataframe.groupby()` is a pandas dataframe, so `grouped_ctk` should be renamed to not imply it is a Thicket.

2024-05-17 16:07 UTC, pearce8 commented
[ ] Address comments on PR
[ ] Make input parameter names clear, make clear which are optional, add --help messages
[ ] Add error checking for parameters
[ ] make_graph should be renamed to make_figure, also take optional parameters for title and label names

2024-05-17 16:26 UTC, pearce8 requested changes

2024-05-17 16:26 UTC, pearce8 commented on examples/python_scripts/stacked_line_graphs.py
> +            filter_df[i, "Avg time/rank"] / filter_df[i, "Avg time/rank"].sum()
This is the sum of the filtered values only.  We should use the sum of all values (before the filter).

2024-05-21 18:47 UTC, michaelmckinsey1 commented on examples/python_scripts/stacked_line_graphs.py
> +    parser.add_argument("--input_files", default="", type=str)
Arguments that are required, such as `input_files`, should have no `default` and `required=True` with a `help` description. It would also be nice to have a program description like this example so users can run `python stacked_line_graphs.py --help`
```suggestion
    parser = argparse.ArgumentParser(
        prog="stacked_line_graphs.py",
        description="Generate stacked line graphs from Caliper files.",
        epilog="This script reads in Caliper files and generates stacked line graphs based on the specified parameters.",
    )
    parser.add_argument("--input_files", required=True, type=str, help="Directory of Caliper files to read in.")
```

2024-05-21 18:54 UTC, michaelmckinsey1 commented on examples/python_scripts/stacked_line_graphs.py
> +    parser.add_argument("--out_graphs", nargs="+")
This one should have the `choices` argument, since you are looking for either `perc` or `total`

```suggestion
    parser.add_argument("--out_graphs", nargs="+", required=True, choices=["perc", "total"], type=str)
```

2024-05-22 22:17 UTC, michaelmckinsey1 requested changes

2024-05-22 22:17 UTC, michaelmckinsey1 commented on examples/python_scripts/stacked_line_graphs.py
> +from hatchet import QueryMatcher
I think the `from`s can technically go at the end of each block, but this is pep8
```suggestion
import argparse
import copy
from glob import glob
import re
import sys

sys.path.append("/usr/gapps/spot/dev/hatchet-venv/x86_64/lib/python3.9/site-packages/")
sys.path.append("/usr/gapps/spot/dev/hatchet/x86_64/")
sys.path.append("/usr/gapps/spot/dev/thicket-playground-dev/")

import hatchet as ht
from hatchet import QueryMatcher
from IPython.display import display, HTML
import matplotlib.pyplot as plt
import pandas as pd

import thicket as th
```

2024-05-22 22:18 UTC, michaelmckinsey1 commented on examples/python_scripts/stacked_line_graphs.py
> +from hatchet import QueryMatcher
The reason why Hatchet and Thicket are separate is because we consider Hatchet a third-party package in relation to Thicket

2024-06-28 18:24 UTC, michaelmckinsey1 commented on docs/examples.rst
> +  :align: center
```suggestion
.. literalinclude:: ../examples/python_scripts/stacked_line_charts.py
    :language: python


To run the script:

.. code:: console

   $ python stacked_line_charts.py --input_files <input file or path> --groupby_parameter <parameter varied between runs> --filter_prefix <optional prefix> --top_ten <optional True|False> --out_graphs <perc|total>


Example output graph

.. figure:: images/perc.png
  :width: 800
  :align: center
```

2024-07-01 21:10 UTC, michaelmckinsey1 requested changes
1. I think we rename `examples.rst` to `canned_analysis.rst` and change the doc title to `Canned Analysis`
2. Is the `examples` directory going to contain other things than python scripts? Otherwise can we remove the `python_scripts` directory level and maybe these scripts are labeled like the tutorial notebooks `01A_display_valid_metadata_metric.py`, `01B_stacked_line_charts.py`.

2024-07-01 21:10 UTC, michaelmckinsey1 commented on examples/python_scripts/display_valid_metadata_metric.py
> +    for value in tk.dataframe.columns:
```suggestion
    for value in tk.performance_cols:
```

2024-07-01 21:10 UTC, michaelmckinsey1 commented on examples/python_scripts/display_valid_metadata_metric.py
Is this a separate example from the other two? It kind of looks like it is meant to be ran before the next one, maybe it should go in the description of `stacked_line_charts.py` to run this script first to make it clearer they are related.

There should be some check for argv, if the user runs the script without arguments. Where `usage_str` is how to use the script.
```
if len(sys.argv) < 2:
    print(usage_str)
    exit()
```

2024-07-01 21:10 UTC, michaelmckinsey1 commented on examples/python_scripts/display_valid_metadata_metric.py
> +from hatchet import QueryMatcher
```suggestion
```

2024-07-01 21:10 UTC, michaelmckinsey1 commented on examples/python_scripts/stacked_line_graphs_deepcopy.py
Is this script an outdated version of `stacked_line_charts.py` with deepcopy instead? Why couldn't we have one script where `deepcopy` is an argument? This would usually be expressed as `inplace` like in pandas.

2024-07-01 21:10 UTC, michaelmckinsey1 commented on examples/python_scripts/stacked_line_charts.py
> +    parser.add_argument("--x_axis_unique_metadata", required=True, default='mpi.world.size', type=str, help="Parameter that is varied during the experiment.")
It is confusing for required arguments to have a default value. If it is required it should not have a default value. If you want it to be an example it should go in the help string for that arg.

2024-07-01 21:10 UTC, michaelmckinsey1 commented on examples/python_scripts/stacked_line_charts.py
> +    parser.add_argument("--chart_xlabel", default="MPI World Size", type=str, help="Optional: X Label of chart.")
The default for `chart_xlabel` should be the `x_axis_unique_metadata` column name correct? considering that is required.

2024-07-01 21:10 UTC, michaelmckinsey1 commented on docs/images/perc.png
Update this chart with labels

2024-07-01 21:10 UTC, michaelmckinsey1 commented on examples/python_scripts/stacked_line_charts.py
> +    parser.add_argument("--top_n", default=-1, type=int, help="Optional: Filters only top n longest time entries to be included in chart.")
I think it would make sense for `filter_prefix` and `top_n` to be like `group_nodes_name`. So instead of "entries" we say "nodes". `filter_nodes_name_prefix` and `top_n_nodes`, descriptions should correspond.

2024-07-01 21:10 UTC, michaelmckinsey1 commented on examples/python_scripts/stacked_line_charts.py
> +    world_size = list(gb.keys())
This will not be `world_size` if `x_axis_unique_metadata` is not `mpi.world.size`. For clarity it should be renamed.

2024-07-31 20:22 UTC, dyokelson commented
@Thionazin your unit tests are failing on flake8 formatting, make sure you run `flake8` and check back in, all checks/unit tests need to pass before we can merge.

2024-07-31 21:02 UTC, dyokelson requested changes

2024-07-31 21:02 UTC, dyokelson commented on docs/examples.rst
> +.. figure:: images/perc.png
Please show all your nicer kripke examples here after this generic example as well, this doc should be structured for each example plot:
1. the exact command line used to generate the plot (including all parameters, so that a user can map what was run to what they see in the output)
2. the output plot image

The doc page should be ordered:
generic example
parameter table
other examples

2024-07-31 21:02 UTC, dyokelson commented on docs/examples.rst
> +.. literalinclude:: ../examples/python_scripts/stacked_line_charts.py
What does this do? Does the user need to run it or is the formatting wrong and it is used for the documentation page?

2024-07-31 21:02 UTC, dyokelson commented on docs/examples.rst
> +  Scaling plot
"Scaling plot" should be deleted

2024-07-31 21:02 UTC, dyokelson commented on docs/examples.rst
> +Example output graph
"Example output graph" can be deleted

2024-07-31 21:02 UTC, dyokelson commented on docs/examples.rst
> +
Right here lets add a text description of what the script does.

2024-07-31 21:02 UTC, dyokelson commented on docs/examples.rst
> +
```suggestion
Thicket can easily create graphs that show the scaling behavior of an application. In thicket/examples/python_scripts/ the python scripts provide examples for how to generate stacked line charts.

Below, we show how to run the script to generate scaling analysis plots.
```

2024-07-31 21:02 UTC, dyokelson commented on docs/examples.rst
> +  Scaling plot
Please add a table here describing all possible input parameters to the script.
Each parameter should have any default values specified as well as an example input

2024-07-31 21:02 UTC, dyokelson commented on docs/images/perc.png
If you want to include this generic example please change this figure so that the axes labels and titles match the parameters. For example, the x-axis label would be groupby_parameter (or the actual value passed in, "x-axis label" or something). It should have a clear mapping from the example of what parameters were passed in on the command line to what shows up in the plot. You may need to add the y-axis and title parameters to the example command line. Also, since you're showing real data I honestly wouldn't try to generalize this too much with random labels and titles, update the x-axis label "MPI World Size", y-axis label "Avg Time (exc)" or whatever metric that is, and title "Scaling behavior for application". Don't use "Horrible Graph title."

2024-07-31 21:02 UTC, dyokelson commented on examples/python_scripts/display_valid_metadata_metric.py
I am confused what this file is for - why is it included? It doesn't seem to be used by the other scripts and it isn't described in the documentation page.

2024-07-31 21:02 UTC, dyokelson commented on examples/python_scripts/stacked_line_charts.py
Does this still work if the user doesn't pass in any additional_args? They are just default values?

2024-07-31 21:02 UTC, dyokelson commented on examples/python_scripts/stacked_line_graphs_deepcopy.py
Can you add a description or example to the documentation about what this file does? I do not understand why someone would use this instead of the stacked_line_charts.py and what it does differently. Or since they are almost the exact same file - as @michaelmckinsey1 mentioned maybe "deepcopy" should be passed as a parameter instead. That way you can just add the deepcopy parameter to the parameter table, combine the functionality into the other script, and delete this script.

2024-08-20 22:53 UTC, dyokelson reviewed
Thanks for the updates @Thionazin, this is looking pretty good to me, just a question for @pearce8 about the strong scaling graph. Also @michaelmckinsey1 can you just go over your comments and let me know if any still apply or otherwise mark them as resolved?

Once those two things are settled I'll approve it for merging.

2024-08-20 22:53 UTC, dyokelson commented on docs/images/kripke_cuda_strong_tot.png
@pearce8 Do these strong scaling results look as expected to you? Shouldn't we be seeing speedup for higher mpi world size? Just wanted to sanity check, in case I'm just missing something. The weak scaling graph looks as I would expect.

2024-10-10 22:01 UTC, michaelmckinsey1 commented
> [ ✓] Address comments on PR
> [ ✓] Make input parameter names clear, make clear which are optional, add --help messages
> [ ✓] Add error checking for parameters
> [ ✓] make_graph should be renamed to make_figure, also take optional parameters for title and label names
> [ ✓] Upload new figures here

2024-10-10 22:46 UTC, michaelmckinsey1 commented on docs/images/kripke_cuda_strong_tot.png
Maybe the problem size was not large enough?

2025-05-02 21:55 UTC, michaelmckinsey1 commented on docs/images/kripke_cuda_strong_tot.png
[5b43acc](https://github.com/LLNL/thicket/pull/153/commits/5b43acc38a23d2845a01a770d1827e106d523d1c) - the script seemed to be using total time metric always

2025-05-02 21:57 UTC, michaelmckinsey1 commented
Depends on https://github.com/LLNL/benchpark/pull/745

2025-05-16 22:06 UTC, michaelmckinsey1 commented
Superceded by https://github.com/LLNL/benchpark/pull/761

2025-05-16 22:06 UTC, closed without merging