Refinements to display_violinplot_thicket Function
LLNL/thicket pull request #156
Opened 2024-05-01 05:56 UTC by Yejashi

This PR improves the display_violinplot_thicket function in two ways:

- Changed default xlabel to 'thicket' for clarity.

- Restricted function to accept only the same node across all provided thickets.

2024-05-08 17:19 UTC, ilumsden requested changes
Most of this looks good, but there are two main issues that need to be addressed before I can approve.

2024-05-08 17:19 UTC, ilumsden commented on thicket/stats/display_violinplot.py
> +
This is likely to cause a lot of errors. To determine if objects are present, sets compute hashes. If you look at [Hatchet's Node class](https://github.com/LLNL/hatchet/blob/6a6d7027056df96bd1c919ab34a9acce81f3b9a1/hatchet/node.py#L190), the hash of a `Node` object (i.e., the type of the objects returned from `nodes.values()`) is just the `_hatchet_nid` field. There is currently no guarantee that `Node` objects representing the same region in two Thickets will have the same `_hatchet_nid` value. For example, a `Node` for e.g., `MPI_Send` could have a `_hatchet_nid` of 5 in one Thicket and 8 in the other.

To fix this, you need to put the `Frame` objects in the set. You can do that with:
```python
if len(set([n.frame for n in nodes.values()])):
```

2024-05-08 17:19 UTC, ilumsden commented on thicket/tests/test_display.py
> +    nodes = {"th_1": node[0], "th_2": node[0], "th_3": node[0]}
This should not work. The nodes passed to `display_violinplot_thicket` should come from the actual Thickets passed to the function. Here, you are getting the nodes from one Thicket (`combined_th`), but you are passing different Thickets (from `thicket_list`) to `display_violinplot_thicket`.

To fix this, you need to get your nodes from `thicket_list[0]`, `thicket_list[1]`, and `thicket_list[2]`.

2024-05-08 17:19 UTC, ilumsden commented on thicket/tests/test_display.py
> +        invalid_nodes = {"th_1": node[1], "th_2": node[0], "th_3": node[0]}
See comment about which nodes you need to capture

2024-05-08 17:19 UTC, ilumsden commented on thicket/tests/test_display.py
> +        false_nodes = {"th_x": node[0], "th_2": node[0], "th_3": node[0]}
See comment about which nodes you need to capture

2024-05-13 15:57 UTC, ilumsden commented
@Yejashi please rebase this PR on #160 or rebase on `develop` after #160 is merged. There is a bug in the re-exports of `display_violinplot.py` that is addressed by #160. If you do not merge the changes from this PR, you will reintroduce the bug.

2024-05-13 16:04 UTC, ilumsden approved these changes
This looks good. @pearce8 just don't merge until my comment regarding #160 is addressed

2024-05-15 17:10 UTC, pearce8 approved these changes

2024-05-15 17:10 UTC, merged