Implementation of query_stats function
LLNL/thicket pull request #157
Opened 2024-05-02 06:34 UTC by Yejashi

2024-05-15 17:37 UTC, ilumsden requested changes
There's one major issue right now with `query_stats` and the corresponding tests:

They don't update or check the statsframe.

Since you are querying the statsframe, I would expect the output Thicket to contain the following:
1. A statsframe containing only nodes captured by the query 
2. A graph containing only nodes captured by the query
3. A performance dataframe containing only nodes captured by the query
4. An unmodified metadata table

Your code right now produces `Thicket` objects with elements 2, 3, and 4, but it doesn't add the filtered statsframe (i.e., element 1) back to the new `Thicket`.

2024-05-15 17:37 UTC, ilumsden commented on thicket/thicket.py
> +        self, query_obj, squash=True, update_inc_cols=True, multi_index_mode="off"
The `multi_index_mode` argument should not be needed for `query_stats`. As of now, the statsframe should only have a one-level row index. `multi_index_mode` is only needed when the DataFrame used in the querying has a multi-level row index.

2024-05-15 17:37 UTC, ilumsden commented on thicket/thicket.py
> +        index_names = self.dataframe.index.names
Why is this line here twice?

2024-05-15 17:37 UTC, ilumsden commented on thicket/thicket.py
> +            return filtered_th.squash(update_inc_cols=update_inc_cols)
At this point, the new `Thicket` object will have:
* A correctly-filtered performance DataFrame
* A correctly-filtered Graph

However, you will have either an empty statsframe or the old statsframe (depending on whether `squash` clears the statsframe).

You need to add code to update the statsframe.

2024-05-15 17:37 UTC, ilumsden commented on thicket/tests/test_query_stats.py
> +    )
You are not checking anything regarding the statsframe here. You need to add code to make sure the statsframe is valid too.

2024-05-15 17:37 UTC, ilumsden commented on thicket/tests/test_query_stats.py
> +    new_th = th_cj.query_stats(query, multi_index_mode="all")
You should not have `multi_index_mode` for `query_stats`

2024-05-20 16:53 UTC, ilumsden requested changes
Very good, but there's still a few things that need to be addressed

2024-05-20 16:53 UTC, ilumsden commented on thicket/tests/test_query_stats.py
> +    assert all([n.frame["name"] in match_names for n in sframe_nodes])
The check on line 50 (see below) should also be duplicated for statsframe:

```python
assert all([n in filt_th_df_nodes for n in filt_nodes])
```

2024-05-20 16:53 UTC, ilumsden commented on thicket/tests/test_query_stats.py
> +    th.stats.mean(new_th, columns=[(1, "Min time/rank")])
Why are you calling `th.stats.mean` again? The statsframe should not be cleared, so, unless I'm missing something, there should be no need to call `mean` again

2024-05-20 16:53 UTC, ilumsden commented on thicket/tests/test_query_stats.py
> +    th.stats.mean(new_th, columns=[(1, "Min time/rank")])
Again, why are you calling `th.stats.mean` here?

2024-05-20 16:53 UTC, ilumsden commented on thicket/thicket.py
> +        ]
You've already done this in a more pandas-native, performant why on line 1213 (i.e., where you define `filtered_sf_df`). Remove this code and just use `filtered_sf_df`

2024-05-20 16:53 UTC, ilumsden commented on thicket/thicket.py
> +        filtered_th.statsframe.dataframe = sframe_copy
If you're going to start with a deepcopy of the input `Thicket` object, you need to also update `filtered_th.statsframe.graph` so that it is the same as `filtered_th.graph`.

2024-06-11 23:30 UTC, ilumsden requested changes
This is very close to being good to go. I've got a few more changes, but I suspect this PR will probably be good after that.

2024-06-11 23:30 UTC, ilumsden commented on thicket/stats/calc_boxplot_statistics.py
> +            )
This is really over-complicated for getting the metric names for multi-level columns. You need to loop over the keys of the inner dictionary and add `str((idx, key))` for each iteration. So:
```python
for k in boxplot_dict[idx]:
    output_column_names.append(str((idx, k)))
```

2024-06-11 23:30 UTC, ilumsden commented on thicket/stats/maximum.py
> +            output_column_names.append(str((idx, column + "_max")))
This applies to more than just this file, but you don't need to pass the tuple through `str()`. A tuple of strings is hashable, so it can be used as a key in the stats cache just as easily as its "stringified" version.

2024-06-11 23:30 UTC, ilumsden commented on thicket/stats/percentiles.py
> +                column_name_agg = column_name_agg + column_to_append
Do not do this. These are all separate columns, so there is no reason to concatenate their names together for the cache. Just do `output_column_names.append(column_to_append)`

2024-06-11 23:30 UTC, ilumsden commented on thicket/stats/percentiles.py
> +                column_name_agg = column_name_agg + str(column_to_append)
See previous comments about `str()` and concatenation

2024-06-11 23:30 UTC, ilumsden commented on thicket/stats/preference.py
> +            aggregated_cols + "_std_preferred" + aggregated_cols + "_mean_preferred"
Again, do not just concatenate these stats metric names. This produces two stats columns, so append two column names

2024-06-11 23:30 UTC, ilumsden commented on thicket/stats/preference.py
> +            str(col_name) + "_std_preferred" + str(col_name) + "_mean_preferred"
Again, no concatenation

2024-06-11 23:30 UTC, ilumsden commented on thicket/stats/stats_utils.py
> +def cache_decorator(func):
Please rename this. This is a really generic name. How about `cache_stats_op`?

2024-06-11 23:30 UTC, ilumsden commented on thicket/tests/test_query_stats.py
> +    assert all([n in filt_th_df_nodes for n in filt_nodes])
The original `assert` just checks if the nodes in the graph form a subset of the nodes in the performance dataframe. The performance dataframe could contain more nodes than the graph and still pass this test.

Instead, change this to:
```python
assert sorted(filt_nodes) == sorted(filt_th_df_nodes)
```

`Node` objects are comparable (comparison is w.r.t their `_hatchet_nid` fields). As a result, you can sort both lists and then use `==` to check that the set of nodes in the Graph and performance dataframe are truly equal.

Note that you can only do this type of comparison when all the nodes come from the same `Thicket` object. There is no guarantee that this will work across `Thicket` objects (e.g., the comparisons involving `match`, `match_frames`, and `match_names` above).

2024-06-11 23:30 UTC, ilumsden commented on thicket/tests/test_query_stats.py
> +    assert all([n in filt_th_df_nodes for n in filt_nodes])
Actually, you may need to make sure that the contents of both are unique first. This won't work if there are duplicates in either list.

2024-06-11 23:30 UTC, ilumsden commented on thicket/tests/test_query_stats.py
> +    assert all([n in pd.unique(filt_th_df_nodes) for n in sframe_nodes])
See the comment above regarding using `==` instead of `all()`. Also, this line provides an example for how to make the lists unique first.

2024-06-11 23:30 UTC, ilumsden commented on thicket/tests/test_stats.py
> +        len(th_1.statsframe_ops_cache[list(th_1.statsframe_ops_cache.keys())[0]]) == 1
There's no need for two tests here. Just copy this line into `test_reapply_statsframe_operations`.

2024-06-11 23:30 UTC, ilumsden commented on thicket/thicket.py
> +                statsframe_ops_cache={},
I'd recommend adding comments here and on line 418 (I'll add a comment there) saying why we reset the cache. Just a useful thing to make sure we don't forget in the future.

2024-06-11 23:30 UTC, ilumsden commented on thicket/thicket.py
> +            combined_thicket.statsframe_ops_cache = {}
Add a comment here too

2024-06-11 23:30 UTC, ilumsden commented on thicket/thicket.py
> +            filtered_th.dataframe = filtered_df
This needs to happen even if we don't squash. If we change the stats data, we should change the perf data.

2024-06-11 23:30 UTC, ilumsden commented on thicket/thicket.py
> +        filtered_th = self.deepcopy()
Given how much we're changing, do we really need a `deepcopy` here? It might be better to just create a brand new `Thicket` object with the filtered statsframe and dataframe, the same graph, and other bookkeeping members copied.

2024-06-11 23:30 UTC, ilumsden commented on thicket/thicket.py
> +        filtered_th = self.deepcopy()
@pearce8 I'd appreciate your feedback here too

2024-06-11 23:30 UTC, ilumsden commented on thicket/thicket.py
> +            return final_thicket
Once `filtered_th.dataframe = filtered_df` is moved outside of this conditional, we can just do all our operations on `filtered_th`. So, this return statement will become redundant.

2024-06-11 23:30 UTC, ilumsden commented on thicket/thicket.py
> +            for k, g in groupby(
Given that we have a `Thicket.groupby` function, it would probably be better to change the import for groupby to just `import itertools` and then change this call to `for k, g in itertools.groupby(...):`

2024-06-11 23:30 UTC, ilumsden commented on thicket/thicket.py
> +                elif arg[1] is None:
Will these ever be `None`? If not, these conditionals aren't needed. Otherwise, these conditions should probably just convert `arg[0]` to `()` and convert `arg[1]` to `{}`.

2024-06-12 00:26 UTC, Yejashi commented on thicket/thicket.py
> +                statsframe_ops_cache={},
No that i think about it, there might not be a reason to reset the cache when a concat with axis set to index is performed. All that really changes is the nodes and not the column.

2024-06-12 16:27 UTC, Yejashi commented on thicket/thicket.py
> +        filtered_th = self.deepcopy()
@ilumsden, suppose i created a new thicket in place of deepcopy, i still need to run squash on it so doesn't that mean there will be three thickets regardless?

2024-06-12 18:19 UTC, michaelmckinsey1 commented on thicket/thicket.py
> +                statsframe_ops_cache={},
```suggestion
```
Why is this line necessary when it will be created in the constructor?

2024-06-12 18:29 UTC, michaelmckinsey1 commented on thicket/thicket.py
> +        filtered_th = self.deepcopy()
I don't see the difference of making a new Thicket as you would need to give the constructor copies of the graph and dataframe anyway.

2024-06-12 23:06 UTC, ilumsden commented on thicket/thicket.py
> +        filtered_th = self.deepcopy()
The graph maybe, but you don't need to give it copies of the dataframes. Passing to a constructor will be pass by reference.

I told Befikir this at lunch, but the reason to avoid `deepcopy` is because you are creating copies of the performance dataframe and (potentially) stats dataframe only to immediately replace them. There's no reason to do that.

2024-06-12 23:07 UTC, ilumsden commented on thicket/thicket.py
> +                statsframe_ops_cache={},
I'd argue this is fine. Like you said, it's not necessary, but it does convey the intent of the call more clearly than just leaving it out.

2024-06-12 23:57 UTC, ilumsden requested changes
I suspect that the next review will be an approval for this PR.

There are just a handful of minor things to change. Most of them amount to removing stringification of multi-level column names for the cache. The remaining changes are just minor one line things.

2024-06-12 23:57 UTC, ilumsden commented on thicket/stats/calc_boxplot_statistics.py
> +            output_column_names.append(str(boxplot_dict.keys()))
You should loop over `boxplot_dict.keys()`. Right now, this code is creating an iterator of strings (although you can think of it like a list) and stringifying it. Instead, you want each key to be added to `output_column_names`

2024-06-12 23:57 UTC, ilumsden commented on thicket/stats/calc_boxplot_statistics.py
> +                output_column_names.append(str((idx, k)))
Why are you stringifying the tuples for multi-indexed columns? Since the contents of the tuples are strings, you can use the `tuple` in the cache without stringification. Also, by stringifying, you render the return from this function unusable by users.

2024-06-12 23:57 UTC, ilumsden commented on thicket/stats/check_normality.py
> +            output_column_names.append(str((idx, column + "_normality")))
See comment about stringification in `calc_boxplot_statistics.py`

2024-06-12 23:57 UTC, ilumsden commented on thicket/stats/correlation_nodewise.py
> +            output_column_names.append(str(column_name))
See comment about stringification in `calc_boxplot_statistics.py`

2024-06-12 23:57 UTC, ilumsden commented on thicket/stats/correlation_nodewise.py
> +            output_column_names.append(str(column_name))
See comment about stringification in `calc_boxplot_statistics.py`

2024-06-12 23:57 UTC, ilumsden commented on thicket/stats/calc_boxplot_statistics.py
> +                output_column_names.append(str((idx, k)))
Actually, I see that you have removed the stringification in some places. Given that, just treat this comment (and the other ones that refer to this) as indicators of places where you missed removing it

2024-06-12 23:57 UTC, ilumsden commented on thicket/stats/mean.py
> +            output_column_names.append(str((idx, column + "_mean")))
See comment about stringification in `calc_boxplot_statistics.py`

2024-06-12 23:57 UTC, ilumsden commented on thicket/stats/median.py
> +            output_column_names.append(str((idx, column + "_median")))
See comment about stringification in `calc_boxplot_statistics.py`

2024-06-12 23:57 UTC, ilumsden commented on thicket/stats/minimum.py
> +            output_column_names.append(str((idx, column + "_min")))
See comment about stringification in `calc_boxplot_statistics.py`

2024-06-12 23:57 UTC, ilumsden commented on thicket/stats/preference.py
> +        output_column_names.append(str(col_name) + "_mean_preferred")
This is similar to the comment about stringification in `calc_boxplot_statistics.py`

When you use `str(col_name)`, you are stringifying the tuple and then adding `"_std_preferred"` or `"_mean_preferred"` to it. To fix this, just copy the indexing into `thicket.statsframe.dataframe` above. So, for example:
```python
str(col_name) + "_std_preferred"
```
would become:
```python
(col_name[0], col_name[1] + "_std_preferred")
```

2024-06-12 23:57 UTC, ilumsden commented on thicket/stats/scoring.py
> +    output_column_names.append(str(("Scoring", stats_frame_column_name)))
See comment about stringification in `calc_boxplot_statistics.py`

2024-06-12 23:57 UTC, ilumsden commented on thicket/stats/std.py
> +            output_column_names.append(str((idx, column + "_std")))
See comment about stringification in `calc_boxplot_statistics.py`

2024-06-12 23:57 UTC, ilumsden commented on thicket/stats/variance.py
> +            output_column_names.append(str((idx, column + "_var")))
See comment about stringification in `calc_boxplot_statistics.py`

2024-06-12 23:57 UTC, ilumsden commented on thicket/tests/test_query_stats.py
> +    assert sorted(pd.unique(filt_th_df_nodes)) == sorted(pd.unique(sframe_nodes))
Since this is passing unit tests, there's no need to change this. But, for future reference, it's usually a good idea to make sure you aren't calling pandas functions on non-pandas types (e.g., `pd.unique(filt_th_df_nodes)`) or vice versa (e.g., `sorted(pd.unique(...))`)

2024-06-12 23:57 UTC, ilumsden commented on thicket/thicket.py
> +            profile_mapping=self.profile_mapping,
I'd copy `self.metadata`, `self.profile`, and `self.profile_mapping` here since they shouldn't be affected by the `squash`.

For `self.metadata`, you do this with `self.metadata.copy()` (with or without `deep=True`; I don't think that really matters here).

For the other two, you can copy with `copy.copy(self.profile)` or `copy.deepcopy(self.profile)`. See Thicket's `copy` and `deepcopy` methods for examples.

2024-06-17 22:23 UTC, ilumsden approved these changes
Looks good! @pearce8 this PR is ready for your review

2024-06-17 23:02 UTC, pearce8 commented
@Yejashi Do we have docs/examples (tutorial?) to go with this PR?
@Yejashi @ilumsden Any further thoughts on how we could enforce that the future functions use the decorator?  Example of using this with a different decorator (e.g., profiling the functions)?

2024-06-17 23:44 UTC, Yejashi commented
@pearce8 , in terms of documentation, there really isn't any meaningful difference on how the stats functions are called. All that's really changed from the user end of things is that the stats functions now return a list of output columns. This is already indicated in the docstrings and but not in the thicket documentation website. A concise sentence could accomplish this task.

In terms of queries, i think we should add a small section in the query portion of the tutorials indicating that the query language can now be used on the statsframe, albeit with a slight difference.

2024-06-18 00:37 UTC, ilumsden commented
@pearce8 I mentioned this on Slack in more detail, but this branch shows an example of using Befikir's cache decorator with other decorators: https://github.com/TauferLab/thicket/tree/memray_decorator_example

2024-06-20 19:46 UTC, pearce8 approved these changes

2024-06-20 19:46 UTC, merged