Add Option to Turn Off _fill_perfdata
LLNL/thicket pull request #168
Opened 2024-06-10 19:42 UTC by michaelmckinsey1

2024-06-11 22:02 UTC, michaelmckinsey1 commented
Need to add unit test.

2024-06-11 22:16 UTC, ilumsden reviewed
I have a few comments/changes, but this mostly looks good.

The one thing I'd mention is that this **will** have a notable impact in performance in some cases. As you said in the initial PR comment, this functionality can substantially increase the number of rows in the performance dataframe. Given how slow pandas is and given that pandas uses a minimum of 2x the memory that a single `DataFrame` _should_ take up, adding a substantial number of nodes **will** slow down **all** of Thicket.

Given that, my one remaining comment (which we'll need to discuss) is that it might be better to keep this off by default. Right now in this PR, users have to opt *out* of this feature, which could destroy Thicket's performance if used in the wrong situation. I'd argue that it's better for users to opt *into* this feature in situations where they know the performance won't be destroyed.

2024-06-11 22:16 UTC, ilumsden commented on thicket/ensemble.py
> +            unify_df = _fill_perfdata(unify_df)
This looks good here. However, I took a second to look at the implementation of `_fill_perfdata` (I didn't realize this was a thing before), and I do see an issue there. In `_fill_perfdata`, there's the following code:
```python
except ValueError as e:
    estr = str(e)
    if estr == "cannot handle a non-unique multi-index!":
        warnings.warn(
            "Non-unique multi-index for DataFrame in _fill_perfdata. Cannot Fill missing rows.",
            RuntimeWarning,
        )
    else:
        raise
```

You should **never** depend on another library's error message to report warnings or errors. All it will take to make this code completely invalid is someone from the `pandas` team deciding to change even one character of this message. Either find another way to check when to throw or warn, or always throw a slightly less descriptive error.

2024-06-11 22:16 UTC, ilumsden commented on thicket/thicket.py
> +        unique_perf_indices = set(new_thicket.dataframe.index.droplevel("node"))
Can you cast a pandas `Index` or `MultiIndex` to a set? This seems like an invalid operation that, at best, is creating a set of size 1 containing the pandas object.

2024-06-11 22:16 UTC, ilumsden commented on thicket/thicket.py
> +            new_thicket = new_thicket.squash()
I'm not sure what this is trying to do. From what I can tell, this is trying to see if the `profile` list is a subset of the unique profile IDs in the performance dataframe index. If that's true, then the dataframe can store profile IDs that aren't in the `Thicket.profile` field.

2024-06-11 22:18 UTC, ilumsden requested changes
Accidentally forget to set "Request changes" on my main review. Refer to the main review for comments.

2024-06-11 22:23 UTC, michaelmckinsey1 commented
> I have a few comments/changes, but this mostly looks good.
> 
> The one thing I'd mention is that this **will** have a notable impact in performance in some cases. As you said in the initial PR comment, this functionality can substantially increase the number of rows in the performance dataframe. Given how slow pandas is and given that pandas uses a minimum of 2x the memory that a single `DataFrame` _should_ take up, adding a substantial number of nodes **will** slow down **all** of Thicket.
> 
> Given that, my one remaining comment (which we'll need to discuss) is that it might be better to keep this off by default. Right now in this PR, users have to opt _out_ of this feature, which could destroy Thicket's performance if used in the wrong situation. I'd argue that it's better for users to opt _into_ this feature in situations where they know the performance won't be destroyed.

It's on by default because the default behavior in Thicket has been to fill the index in the performance table. Actually, the default behavior _originally_ was to not fill the index, then there was a design decision made at some point to fill it all the time. My goal with this PR is to at least give the user the option, based on their data.

2024-06-11 22:27 UTC, ilumsden commented
Wait, really? In that case, what you have in this PR is fine, but I will second guess that decision. I suspect we haven't run into any major performance issues because we've just used effectively _N_ copies of the same program. But, once we run into less homogeneous data (e.g., MPMD-style data like what my benchmark will create), we will likely start running into major performance issues with this decision.

2024-06-11 22:29 UTC, michaelmckinsey1 commented on thicket/thicket.py
> +            new_thicket = new_thicket.squash()
This is detecting if `fill_perfdata` is off. To make it more clear I thought of a couple options:

1. I could make it a helper function with a docstring to make it more clear.
2. Have a boolean thicket attribute for `fill_perfdata` that can be checked here.

The purpose of this is that there is a case when the index is not full, and a filter is performed on the metadata that nodes disappear from the performance data, if the metadata for those profiles was filtered out. The code above will update the graph using squash if this happens.

2024-06-11 22:34 UTC, michaelmckinsey1 commented on thicket/thicket.py
> +        unique_perf_indices = set(new_thicket.dataframe.index.droplevel("node"))
Yes you can.

![image](https://github.com/LLNL/thicket/assets/32579379/46f37c3d-abcc-47ae-8cc6-52615106e456)

The set of the index is all of the unique values in the index.

2024-06-11 22:35 UTC, ilumsden commented on thicket/thicket.py
> +            new_thicket = new_thicket.squash()
So, if I'm understanding right, what you're trying to do is 1) check if any nodes were removed from the performance data as a side effect of filtering profiles from the metadata and 2) fix the graph with `squash` if any nodes were removed?

2024-06-11 22:38 UTC, ilumsden commented on thicket/thicket.py
> +            new_thicket = new_thicket.squash()
If what I wrote above is correct, then this code will not do what you're wanting.

2024-06-11 22:39 UTC, ilumsden commented on thicket/thicket.py
> +            new_thicket = new_thicket.squash()
This code (assuming the `set(Series)` thing works) only checks if `Thicket.profiles` is a subset of the profile IDs in the performance dataframe index. That tells you nothing about the nodes.

2024-06-11 22:58 UTC, michaelmckinsey1 commented on thicket/thicket.py
> +            new_thicket = new_thicket.squash()
It tells you if there are profiles in the performance dataframe that do not exist in `tk.profile`. For example if I simulate removing a profile from the dataframe, it will be false which will trigger a squash:

![image](https://github.com/LLNL/thicket/assets/32579379/6d288505-30f8-4a3f-9370-3372f32ec76f)

The actual issue I noticed with this is that they will both always be in sync due to `_sync_profile_components`. So what I should check here instead is if `len(tk.graph) == len(tk.dataframe.index.get_level_values("node").unique())` which is more explicit anyway. These sort of things will get caught when I add unit tests.

2024-06-11 23:05 UTC, michaelmckinsey1 commented on thicket/ensemble.py
> +            unify_df = _fill_perfdata(unify_df)
I made an issue for this https://github.com/LLNL/thicket/issues/172.

2024-06-11 23:31 UTC, ilumsden commented on thicket/ensemble.py
> +            unify_df = _fill_perfdata(unify_df)
Sounds good

2024-06-11 23:32 UTC, ilumsden commented on thicket/thicket.py
> +        unique_perf_indices = set(new_thicket.dataframe.index.droplevel("node"))
Huh. I wouldn't have expected that to work. Pandas usually gets very finicky when applying normal Python operations to `Series`. This works for me.

2024-06-11 23:38 UTC, ilumsden commented on thicket/thicket.py
> +            new_thicket = new_thicket.squash()
Your code is not checking if there are profiles in the dataframe that don't exist in `tk.profile`. It's checking if there are profiles in `tk.profile` that don't exist in the dataframe. It's a subtle difference, but it would allow e.g., the dataframe to contain extra profiles that don't exist in `tk.profiles`.

I actually just encountered this same type of thing in Befikir's `query_stats` PR (#157), and I realized there's a better way to do this check:
```python
sorted(tk.profile) == sorted(unique_perf_indices.tolist())
```

This will check that both the dataframe and `tk.profile` agree in terms of contents and length. `Node` objects are comparable via their `_hatchet_nid` fields. As a result, the `Node` objects within different parts *of the same `Thicket` object* can be compared in this way. This comparison will **not** work across `Thicket` objects though because there's no guarantee that equivalent `Node` objects will have the same `_hatchet_nid` values.

2024-06-12 00:45 UTC, michaelmckinsey1 commented on thicket/thicket.py
> +            new_thicket = new_thicket.squash()
> It's checking if there are profiles in tk.profile that don't exist in the dataframe.

But that is what I was trying to accomplish with that code. That would indicate that there are missing profiles in the performance data, which is what I was saying. However, it doesn't address 

> it would allow e.g., the dataframe to contain extra profiles that don't exist in tk.profiles.

which your correct would be an issue, if not for `_sync_profile_components` being called earlier. Regardless, what I was actually trying to do is check nodes so I'm using a different check now.

2024-06-12 00:47 UTC, michaelmckinsey1 commented on thicket/thicket.py
> +            new_thicket = new_thicket.squash()
For reference, if we are trying to update the state of the profiles in a Thicket we should be using `_sync_profile_components`. And if we are trying to validate properties about the state of a Thicket we should use `validate_profile` or `validate_dataframe` in `utils.py`

2024-06-17 22:29 UTC, ilumsden commented on thicket/thicket.py
> +            new_thicket = new_thicket.squash()
If you're 100% positive that you've ensured the graph and dataframe contain the same node objects, then this is fine.

2024-06-17 22:29 UTC, ilumsden approved these changes
Looks good, so long as we are positive that the `Node` objects are the same across thicket components.

2024-06-18 00:17 UTC, michaelmckinsey1 commented
> Looks good, so long as we are positive that the `Node` objects are the same across thicket components.

They should be unless there is a bug. `utils.validate_nodes` is a function that checks this particular property. If we wanted to be 100% sure, I think we would have to check properties we want to enforce about a Thicket before and after operations like `filter_metadata`, which could be expensive. I am open to this idea though, as it would help catch bugs.

2024-06-18 01:08 UTC, michaelmckinsey1 commented
> > Looks good, so long as we are positive that the `Node` objects are the same across thicket components.
> 
> They should be unless there is a bug. `utils.validate_nodes` is a function that checks this particular property. If we wanted to be 100% sure, I think we would have to check properties we want to enforce about a Thicket before and after operations like `filter_metadata`, which could be expensive. I am open to this idea though, as it would help catch bugs.

I just realized we had a basically identical discussion in https://github.com/LLNL/thicket/pull/173#discussion_r1643134992. I agree that this is a broader issue than both of these PRs.

2024-06-20 19:56 UTC, pearce8 approved these changes

2024-06-20 19:56 UTC, merged