Speedup Reader by Splitting Data into Chunks
LLNL/thicket pull request #170
Opened 2024-06-11 00:37 UTC by michaelmckinsey1

This PR extends off an idea in #169. Limiting the total size of the ensemble during unification is more impactful than any parallelism, and this solution is less complicated than using `multiprocessing`.

```
sequential (1 part): 16,330 files takes 120 minutes
sequential (32 parts): 16,330 files takes 5 minutes
```

2024-06-11 20:23 UTC, michaelmckinsey1 commented on thicket/thicket.py
> +        tk_limit = 2**9
need to figure out a good way to set this value

2024-06-20 17:37 UTC, ilumsden requested changes
The code is good, but something has to be done to make the tree-based concatenation clearer. At bare minimum, this needs to be well commented, otherwise no one is going to have a clue what this is doing.

2024-06-20 17:37 UTC, ilumsden commented on thicket/thicket.py
> +        pbar = tqdm.tqdm(range(len(ens_list) - 1), disable=disable_tqdm)
Using `tqdm` here makes this process **very** hard to understand. I'd suggest not using `tqdm` and/or extensively documenting this with comments.

2024-06-24 22:20 UTC, michaelmckinsey1 commented on thicket/thicket.py
> +        pbar = tqdm.tqdm(range(len(ens_list) - 1), disable=disable_tqdm)
`tqdm` is really useful to see what is happening for longer reads.

I changed it to use a while loop, which should be clearer with the popping and appending that is happening in the loop. And I added very detailed comments.

2024-06-26 21:56 UTC, ilumsden approved these changes
LGTM. The stuff you're doing with tqdm also makes much more sense now that you've added the comments and switched to a `while` loop

2024-06-26 23:32 UTC, ilumsden commented
@pearce8 this PR is also ready for your review

2024-06-26 23:52 UTC, pearce8 approved these changes

2024-06-26 23:52 UTC, merged