Enable Filtering From List of Profiles
LLNL/thicket pull request #173
Opened 2024-06-12 01:17 UTC by michaelmckinsey1

I have came across the need to filter the Thicket based on profiles, and I have been using a roundabout way:
```
# Filter the metadata table based on list of profiles
tk.metadata = tk.metadata.apply(lambda meta: meta[meta.index.isin(profile_list)], axis=0)
# Synchronize the rest of the components
tk._sync_profile_components(tk.metadata)
```
So I designed an explicit function for this filtering `filter_profile`.

2024-06-12 23:33 UTC, ilumsden requested changes
Mostly looks good. Just a few minor changes.

2024-06-12 23:33 UTC, ilumsden commented on thicket/thicket.py
> +        new_thicket = self.copy()
Should this be `copy()` or `deepcopy()`? In the case of `copy()`, the graph is shared between the input Thicket (i.e., `self`) and `new_thicket`. So, if either Thicket object edits its graph, the change will be reflected in the other Thicket.

2024-06-12 23:33 UTC, ilumsden commented on thicket/thicket.py
> +            new_thicket.dataframe.index.get_level_values("node").unique()
Are you 100% positive that the actual `Node` objects in `new_thicket.graph` and `new_thicket.dataframe` are the same here? If not, then this check is invalid because it only sees if there's the same number of nodes, not if the nodes themselves are the same.

An alternative to check for both would be:
```python
sorted(new_thicket.graph.traverse()) == sorted(new_thicket.dataframe.index.get_level_values("node").unique().tolist())
```

2024-06-12 23:33 UTC, ilumsden commented on thicket/thicket.py
>                  pset = set()
I get why this is a set here, but cast it to a `list` or `tuple` before assigning to `profile_truth` for consistency. You could potentially run into issues having `profile_truth` be a `list` sometimes and a `set` others.

2024-06-12 23:33 UTC, ilumsden commented on thicket/thicket.py
>          return self
Why do you return `self` here? Is it for method chaining? If not, I don't really get the purpose of doing this.

2024-06-13 19:06 UTC, michaelmckinsey1 commented on thicket/thicket.py
> +        new_thicket = self.copy()
Good catch. Objects should not be shared between the two Thickets. I realized this same issue was in the other filter functions so I made https://github.com/LLNL/thicket/pull/175

2024-06-13 19:22 UTC, michaelmckinsey1 commented on thicket/thicket.py
> +            new_thicket.dataframe.index.get_level_values("node").unique()
This function will not modify the `Node` objects in a Thicket `graph` and `dataframe`. The only possible case is that `_sync_profile_components` would _remove_ nodes in the dataframe where `fill_perfdata=False`. If the `Node` objects in a Thicket `graph` and `dataframe` are not the same that would be an invalid state for a Thicket coming into this function (which `utils.validate_nodes` would be able to catch, although we are not calling it here).

So the short answer is what you are proposing is not possible unless the Thicket calling `filter_profile` is already invalid. Right now, the utils functions `validate_dataframe`, `validate_profile`, and `validate_nodes` are only called after operations applicable to each one for performance, but maybe we should be validating these properties at the beginning and end of Thicket funcitons.

2024-06-13 19:28 UTC, michaelmckinsey1 commented on thicket/thicket.py
>                  pset = set()
Python is magical! Fixed in [6bf7ce8](https://github.com/LLNL/thicket/pull/173/commits/6bf7ce824458638297c0fcac9590a65397e00810)

2024-06-13 19:32 UTC, michaelmckinsey1 commented on thicket/thicket.py
>          return self
There is no specific reason. I think it could be void. Is there a specific problem you had in mind or just for clarity?

2024-06-17 17:04 UTC, ilumsden commented on thicket/thicket.py
> +            new_thicket.dataframe.index.get_level_values("node").unique()
I get your point, and I agree that checking this when not needed would hurt performance. I think this is a broader discussion than we need for this PR. We should come back to this at some point, but this is fine for this PR.

2024-06-17 17:21 UTC, ilumsden commented on thicket/thicket.py
>          return self
In general, especially given that Python is duck typed, it's better to not return stuff if it's not supposed to be used by the user. So, for example, returning `self` should only be done if you intend for the user to use that return value for e.g., method chaining. If you start returning stuff when you don't have to, it gets really confusing for users really fast.

2024-06-17 17:21 UTC, ilumsden commented on thicket/thicket.py
> +        new_thicket = self.copy()
Awesome

2024-06-17 17:22 UTC, ilumsden approved these changes
I'd still remove the `return self` (as I mentioned in the last review), but otherwise this looks good

2024-06-17 22:00 UTC, pearce8 approved these changes

2024-06-17 23:04 UTC, pearce8 requested changes
Are there docs/test/examples for this functionality?

2024-06-17 23:05 UTC, pearce8 commented on thicket/thicket.py
>          return self
Lets change it to void then.

2024-06-18 17:34 UTC, michaelmckinsey1 commented
> Are there docs/test/examples for this functionality?

No. This PR needs unit tests.

2024-06-24 20:54 UTC, michaelmckinsey1 commented on thicket/thicket.py
>          return self
Done in [1758146](https://github.com/LLNL/thicket/pull/173/commits/1758146dbe57c3ff6011eda391d29a9765428543)

2024-07-02 03:26 UTC, michaelmckinsey1 commented
> > Are there docs/test/examples for this functionality?
> 
> No. This PR needs unit tests.

Unit tests in [f0b2f50](https://github.com/LLNL/thicket/pull/173/commits/f0b2f50ec965a45f3f205a1c56f541a4a057fe7c)

2024-07-10 16:44 UTC, pearce8 approved these changes

2024-07-10 16:44 UTC, merged