Add Nodes in Slice Before Printing Tree
LLNL/thicket pull request #181
Opened 2024-06-24 17:22 UTC by michaelmckinsey1

2024-06-25 21:08 UTC, michaelmckinsey1 commented
Error found from #182

2024-06-26 22:06 UTC, ilumsden requested changes
Mostly looks good. Just a couple of minor changes to ensure good performance and prevent unintended modification of the Thicket data structure.

2024-06-26 22:06 UTC, ilumsden commented on thicket/thicket.py
> +            slice_df = _fill_perfdata(self.dataframe)
Before calling `_fill_perfdata`, I would filter the dataframe down to just the columns that will be involved in the printing. Otherwise, you could be filling in the entire dataframe when you only need to fill in one or two columns.

2024-06-26 22:06 UTC, ilumsden commented on thicket/utils.py
> +        df = df.reindex(
Do not reassign to `df` here. By doing that, all changes you make in this function will be propagated back to the input. For example, when you call `_fill_perfdata(self.dataframe)` in `Thicket.tree`, this line of code causes you to fill in the dataframe in the Thicket object, not just a copy.

2024-07-01 22:37 UTC, michaelmckinsey1 commented on thicket/utils.py
> +        df = df.reindex(
[83ac9cf](https://github.com/LLNL/thicket/pull/181/commits/83ac9cf2c6381bc1ae4a88e704c7599866622e05) fixes this

2024-07-01 23:47 UTC, michaelmckinsey1 commented on thicket/thicket.py
> +            slice_df = _fill_perfdata(self.dataframe)
I tried this in 650007a. It is not trivial to select the columns, because there are 4 different dataframe columns as arguments to tree, default arguments may not exist, and `metric_column` can be a `list` or a `str`.

I collected some performance numbers below for this specific change. I tried to make up examples where `_fill_perfdata` would be doing significant work.

### Testing how long Thicket.tree takes to return (without printing)

#### 1 LBANN file + adding arbitrary columns to stress test (6558 nodes, 110 cols)
without change (3 trials): 
- 3.34s, 3.36s, 3.45s

with 650007a (3 trials):
- 2.9s, 2.8s, 3.16s

#### Contrived example with two different datasets (1 LBANN + 16 AMG) + adding arbitrary columns (6575 nodes, 114 columns)
without: 3.25s
with 650007a: 2.56s

2024-07-02 21:10 UTC, ilumsden approved these changes
LGTM.

However, @pearce8, when you do your review, you should take a look at the comment @michaelmckinsey1 left regarding performance.

2024-07-02 21:10 UTC, ilumsden commented on thicket/utils.py
> +    new_df = df.copy()
This is fine for now, although it may cause issues in the future if we ever start including data beyond POD. That's because `DataFrame.copy` with default arguments performs a shallow copy. So, any by-reference objects in `new_df` that are edited would be edited in `df` as well.

However, we currently don't deal with by-reference objects (besides the nodes, but that can be safely ignored in this case), and I can't see any scenario in the near future where we would. So, we should keep this in mind, but I don't think anything has to be done about this in this PR.

2024-07-02 21:10 UTC, ilumsden commented on thicket/thicket.py
> +                ]
If you really want to shorten the code (at the expense of some readability), you could do this:
```python
df_cols = [
    col
    for col in [
        *metric_column if isinstance(metric_column, list) else metric_column,
        annotation_column,
        name_column,
        context_column,
    ]
    if col in self.dataframe.columns
]
```

2024-07-03 00:09 UTC, michaelmckinsey1 commented on thicket/thicket.py
> +                ]
`*metric_column if isinstance(metric_column, list) else metric_column` isn't valid syntax here. closest I can get is:

```
tree_cols = (
    metric_column
    if isinstance(metric_column, list)
    else [metric_column]
    + [
        annotation_column,
        name_column,
        context_column,
    ]
)
df_cols = [col for col in tree_cols if col in self.dataframe.columns]
```

2024-07-03 00:12 UTC, michaelmckinsey1 commented on thicket/utils.py
> +    new_df = df.copy()
Would the solution you propose be our own function for deepcopying Pandas DataFrames?

2024-07-05 18:34 UTC, ilumsden commented on thicket/utils.py
> +    new_df = df.copy()
No, the solution would be `new_df = df.copy(deep=True)`. However, don't worry about adding that in this PR. We'll only run into this is we make pretty major changes to the types of data being stored in the dataframe. I can't see that happening in the foreseeable future.

2024-07-05 18:40 UTC, ilumsden commented on thicket/thicket.py
> +                ]
Huh. Learn something new every day. Apparently, the `*` unpack operator has to apply to the entire expression. You could rewrite what I have above as the following, and it should work:
```python
df_cols = [
    col
    for col in [
        *(metric_column if isinstance(metric_column, list) else [metric_column]),
        annotation_column,
        name_column,
        context_column,
    ]
    if col in self.dataframe.columns
]
```

2024-07-05 21:49 UTC, michaelmckinsey1 commented on thicket/utils.py
> +    new_df = df.copy()
I thought you were referring to the fact that `deep=True` [does not copy recursively](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.copy.html#:~:text=When%20deep%3DTrue%2C%20data%20is%20copied%20but%20actual%20Python%20objects%20will%20not%20be%20copied%20recursively%2C%20only%20the%20reference%20to%20the%20object.%20This%20is%20in%20contrast%20to%20copy.deepcopy%20in%20the%20Standard%20Library%2C%20which%20recursively%20copies%20object%20data%20(see%20examples%20below).). `deep=True` is the default so that change wouldn't do anything. 

However, `copy.deepcopy` is apparently recursive.

2024-07-05 21:54 UTC, michaelmckinsey1 commented on thicket/thicket.py
> +                ]
works for me [7d8b397](https://github.com/LLNL/thicket/pull/181/commits/7d8b397935395270ef96063d657e4adc6d720d78)

2024-07-10 17:31 UTC, pearce8 approved these changes

2024-07-10 17:31 UTC, merged