Run Unit Tests for Different Parameters
LLNL/thicket pull request #182
Opened 2024-06-24 19:11 UTC by michaelmckinsey1

2024-07-09 21:46 UTC, michaelmckinsey1 commented
Depends on #193

2024-07-09 22:05 UTC, michaelmckinsey1 commented
depends on #181

2024-07-17 02:38 UTC, ilumsden reviewed
This looks good, but there are a couple of things I'd like you to clarify @michaelmckinsey1.

2024-07-17 02:38 UTC, ilumsden commented on thicket/tests/test_concat_thickets.py
> +def test_filter_stats_concat_thickets_columns(thicket_axis_columns, intersection):
Why is `fill_perfdata` not in this test case?

2024-07-17 02:38 UTC, ilumsden commented on thicket/tests/test_concat_thickets.py
> +def test_query_concat_thickets_columns(thicket_axis_columns, intersection):
Same here. Why is `fill_perfdata` not in this test case?

2024-07-17 02:38 UTC, ilumsden commented on thicket/tests/test_intersection.py
> +def test_intersection(rajaperf_cali_1trial, fill_perfdata):
I would ask why this test case doesn't have `intersection`, but this one makes sense

2024-07-17 18:49 UTC, michaelmckinsey1 commented
@ilumsden Tests that use the `thicket_axis_columns` fixture are already parametrized, since `thicket_axis_columns` is parametrized itself. Unlike the other fixtures, which are lists of files, `thicket_axis_columns` and `stats_thicket_axis_columns` create the Thickets in the fixtures. 

So running `python -m pytest thicket/tests/test_concat_thickets.py::test_filter_stats_concat_thickets_columns` results in:
```
0.44s call     thicket/tests/test_concat_thickets.py::test_filter_stats_concat_thickets_columns[Intersection-FillPerfdata]
0.41s call     thicket/tests/test_concat_thickets.py::test_filter_stats_concat_thickets_columns[Intersection-NoFillPerfdata]
0.33s call     thicket/tests/test_concat_thickets.py::test_filter_stats_concat_thickets_columns[Union-FillPerfdata]
0.33s call     thicket/tests/test_concat_thickets.py::test_filter_stats_concat_thickets_columns[Union-NoFillPerfdata]
```

2024-07-17 20:08 UTC, michaelmckinsey1 commented on thicket/thicket.py
> +            return tkc
@ilumsden Do you think this can be a query? This code works but I was not successful at making a query.

This is performing an intersection when the columns are MultiIndex, which can be identified when all of the metric values for a given header are NA like the three rows seen below under the `l` header.

![image](https://github.com/user-attachments/assets/472110ab-b258-4fd6-9edd-6a38e42e1960)

I don't recall if there is support for MultiIndex columns in the query language.

2024-07-17 20:09 UTC, michaelmckinsey1 commented on thicket/tests/test_concat_thickets.py
> +def test_filter_stats_concat_thickets_columns(thicket_axis_columns, intersection):
see https://github.com/LLNL/thicket/pull/182#issuecomment-2234018765

2024-07-22 02:23 UTC, ilumsden commented on thicket/thicket.py
> +            return tkc
There is support for MultiIndex columns in the QL nowadays, but I would not recommend doing this with the QL unless it's really needed. If we care about performance, the QL shouldn't be used for everything. At the end of the day, the problem that the QL is solving (a special variant of subgraph isomorphism) is an NP-Hard problem. Although I can make the QL faster, it will never be super fast due to that fact.

The QL should be used when you need to select or filter a Thicket _while considering the node relationships encoded in the graph_. If you don't need to take those relationships into account, then the QL could introduce unnecessary bottlenecks or slowdowns into your code. A good example of when you _should_ use the QL is what you do in `NCUReader` @michaelmckinsey1. A good example of when you _should not_ use the QL is when you just want to apply a filter to each node independently.

Besides all that stuff related to the QL, I'd also recommend you don't do the mentioned change in this PR. That's a different change to the code, so it would belong in a different PR if you were to do it.

2024-07-22 02:30 UTC, ilumsden requested changes
Got a few more changes that I'd like you to make. The most notable is that I'd encourage you to remove the use of the QL in `Thicket.intersection` since you are already editing it.

2024-07-22 02:30 UTC, ilumsden commented on thicket/tests/conftest.py
> +        calltree=["union", "intersection"][intersection],
Since we're not in C, please don't do the whole "True can be interpreted as 1 and False can be interpreted as 0" thing. This code does work, but it is unbelievably unintuitive. I had to stare at it for 5 minutes before I realized what you were doing.

The normal way to do this in Python is:
```python
calltree="intersection" if intersection else "union",
```

2024-07-22 02:30 UTC, ilumsden commented on thicket/tests/conftest.py
> +        calltree=["union", "intersection"][intersection],
See other comment about this syntax

2024-07-22 02:30 UTC, ilumsden commented on thicket/thicket.py
> +                query = Query().match(".", lambda df: len(df) == len(self.profile))
I didn't see this before. I get why you were asking about using the QL with MultiIndex now. I'd still recommend not using the QL here. At the end of the day, it's almost always better to use _P_ code than _NP Hard_ code.

2024-07-22 02:31 UTC, ilumsden commented on thicket/thicket.py
> +            return tkc
Ignore my point about not changing this in this PR. I hadn't gone over your changes before I said that. My comment about not using the QL willy-nilly stands though.

2024-07-22 20:37 UTC, michaelmckinsey1 commented on thicket/tests/conftest.py
> +        calltree=["union", "intersection"][intersection],
sure 6df4876

2024-07-22 20:37 UTC, michaelmckinsey1 commented on thicket/tests/conftest.py
> +        calltree=["union", "intersection"][intersection],
6df4876

2024-07-22 20:52 UTC, michaelmckinsey1 commented on thicket/thicket.py
> +                query = Query().match(".", lambda df: len(df) == len(self.profile))
Actually, we do need the QL because the code that doesn't use the QL does not consider the relationships. Consider this example where I set a parent nodes values to be NaN:

```
1.781 RAJAPerf
├─ nan Algorithm
│  ├─ 0.002 Algorithm_MEMCPY
│  ├─ 0.002 Algorithm_MEMSET
│  ├─ 0.003 Algorithm_REDUCE_SUM
```

becomes

```
1.781 RAJAPerf
├─ 0.002 Algorithm_MEMCPY
├─ 0.002 Algorithm_MEMSET
├─ 0.003 Algorithm_REDUCE_SUM
```

when it should be 

```
1.781 RAJAPerf
```

2024-07-22 21:52 UTC, michaelmckinsey1 commented on thicket/thicket.py
> +                query = Query().match(".", lambda df: len(df) == len(self.profile))
I prefer using the QL where I can, because it is better tested and more readable than writing new code like in this PR. I suppose then you would think that code block would benefit from us having a performance data filter function, and not from the QL? And a performance data filter would also replace the queries in intersection?

2024-08-12 14:02 UTC, ilumsden commented on thicket/thicket.py
> +                query = Query().match(".", lambda df: len(df) == len(self.profile))
Going back and trying to knock out some of these reviews now.

A performance data filter function (similar to Hatchet's `filter` function) would be a great thing to have. At the end of the day, if you are doing filtering that doesn't care about the structure of the graph, you really should be using Pandas operations over the QL, and that's what this type of function would provide. I have some thoughts on how to improve the QL's performance, but it should still never be faster than Pandas on single node filtering (unless Pandas is **much** worse in performance than I think).

That being said I do get your point about using the QL in this case. I think a good thing to do here would be to continue using the QL in `intersection` (for now at least, we may revisit later) and then create a performance data filter function.

2024-08-12 14:05 UTC, ilumsden approved these changes
LGTM, but see my last comment regarding performance data filtering and the QL.

@pearce8 this PR is ready for your review.

2024-10-25 13:33 UTC, slabasan commented
@michaelmckinsey1 Can you please resolve conflicts on this PR?

2024-10-28 17:49 UTC, slabasan approved these changes

2024-10-28 17:50 UTC, merged