Optimize Unify
LLNL/thicket pull request #185
Opened 2024-06-26 05:01 UTC by michaelmckinsey1

2024-06-26 22:22 UTC, ilumsden requested changes
Mostly looks good. Just one issue that needs to be addressed to ensure we don't run into unexpected (and possibly undefined) behavior.

2024-06-26 22:22 UTC, ilumsden commented on thicket/ensemble.py
> +                    old_to_new[cur_id] = temp_dict[new_id]
Never update the thing you are iterating over. You may get lucky, but 9 times out of 10, this is at best undefined behavior.

2024-06-26 22:30 UTC, michaelmckinsey1 commented on thicket/ensemble.py
> +                    old_to_new[cur_id] = temp_dict[new_id]
Good catch I messed up when converting it from a function [a1479b3](https://github.com/LLNL/thicket/pull/185/commits/a1479b3094970375e92c378f95dc169207610518)

2024-06-26 23:29 UTC, ilumsden approved these changes
LGTM

2024-06-26 23:29 UTC, ilumsden commented
@pearce8 this PR is ready for your review

2024-06-27 01:42 UTC, pearce8 approved these changes

2024-06-27 01:42 UTC, merged