Fix Deepcopy Bug
LLNL/thicket pull request #190
Opened 2024-07-05 18:31 UTC by michaelmckinsey1

In Thicket, we assume 
```
self.graph is self.statsframe.graph
```
current `deepcopy()` breaks this assumption and this is a fix.

2024-07-05 18:46 UTC, ilumsden requested changes
Good catch. I've got one very minor change that should be made, but looks good otherwise.

2024-07-05 18:46 UTC, ilumsden commented on thicket/thicket.py
> +                graph=gf.graph, dataframe=self.statsframe.dataframe.copy()
Since this is a deepcopy operation, we should use a dataframe deepcopy too. Change the dataframe piece of this line to:
```python
dataframe=self.statsframe.dataframe.copy(deep=True)
```

2024-07-05 21:13 UTC, michaelmckinsey1 commented on thicket/thicket.py
> +                graph=gf.graph, dataframe=self.statsframe.dataframe.copy()
It is [deep by default](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.copy.html). Is this just to be explicit?

2024-07-08 16:56 UTC, ilumsden approved these changes
LGTM

2024-07-10 18:00 UTC, pearce8 approved these changes

2024-07-10 18:00 UTC, merged