Add root node
LLNL/thicket pull request #192
Opened 2024-07-09 19:48 UTC by michaelmckinsey1

2024-07-09 19:48 UTC, michaelmckinsey1 commented
Depends on #190 and #173

2024-07-11 00:09 UTC, ilumsden requested changes
Mostly looks good.

The only change that really _needs_ to be made is the one about `pop()`. The other two are just suggestions.

2024-07-11 00:09 UTC, ilumsden commented on thicket/thicket.py
> +        )
If you're going to do `frame.Frame`, why not also do `node.Node`? Or, better yet, just do the imports in a way that let's you do `Node` and `Frame`.

2024-07-11 00:09 UTC, ilumsden commented on thicket/thicket.py
> +        self.reapply_stats_operations()
I have one issue and one thing I think is odd with this function.

First, this function will not properly set the `_depth` field of the `Node`. This won't cause issues with much of Thicket, but there are a few places (e.g., certain queries with query language) where this could cause issues.

Second, it's odd that this function makes the new root node have the largest `_hatchet_nid` field in the `Thicket` object. It's not an issue, but it is odd.

There are two functions from Hatchet that can help with this. `hatchet.Graph.enumerate_depth` will traverse the graph and update the `_depth` field for all nodes. `hatchet.Graph.enumerate_traverse` will traverse the graph and update the `_hatchet_nid` fields for all nodes. `enumerate_traverse` also calls `enumerate_depth`.

2024-07-11 00:09 UTC, ilumsden commented on thicket/thicket.py
> +        return node.pop()
It would be better to just return `node[0]`. `pop` will do things like resizing (see the [source code](https://github.com/python/cpython/blob/5c22476c01622f11b7745ee693f8b296a9d6a761/Objects/listobject.c#L1021)), which isn't needed.

2024-07-11 02:43 UTC, pearce8 commented on thicket/thicket.py
> +        self.reapply_stats_operations()
I am not worried about the largest nid, but the depth should be verified and correct for all of the nodes after this operation.

More importantly, I am not sure about the interface.  If adding a root node, what becomes its children?  All the nodes that were previously root nodes?

2024-07-11 19:14 UTC, michaelmckinsey1 commented on thicket/thicket.py
> +        return node.pop()
[e2d957c](https://github.com/LLNL/thicket/pull/192/commits/e2d957cd265d0b6b25bbba6c7d949a0fcbf761ed)

2024-07-11 19:34 UTC, michaelmckinsey1 commented on thicket/thicket.py
> +        )
I was using `node.Node` but we use `node` as a variable name in squash and I'm using it in `get_node()`. Not a big deal, so I'll just import `Node` and `Frame`

[7e56d11](https://github.com/LLNL/thicket/pull/192/commits/7e56d11403fc4f7ca4cf848cf0ae19076700d538)

2024-07-11 19:48 UTC, michaelmckinsey1 commented on thicket/thicket.py
> +        self.reapply_stats_operations()
Good catch, depth was not being set. Now calling `self.graph.enumerate_traverse()` to set depth and hatchet nid.

2024-07-11 20:02 UTC, michaelmckinsey1 commented on thicket/thicket.py
> +        self.reapply_stats_operations()
> I am not worried about the largest nid, but the depth should be verified and correct for all of the nodes after this operation.
> 
> More importantly, I am not sure about the interface. If adding a root node, what becomes its children? All the nodes that were previously root nodes?

Children would not be a concern in this case, since we are adding a root node with no children and no parents. The other root nodes will be the siblings of the new root node. Adding A node anywhere in the tree would be more involved than this function.

2024-07-22 02:40 UTC, ilumsden requested changes
This mostly looks good at this point. Just a couple of minor changes.

2024-07-22 02:40 UTC, ilumsden commented on thicket/tests/test_add_root_node.py
> +    tk, tk2, tk3 = literal_thickets
Since you're not using `tk2` or `tk3`, change this line to the following:

```python
tk, _, _ = literal_thickets
```

2024-07-22 02:40 UTC, ilumsden commented on thicket/tests/test_get_node.py
> +    tk, tk2, tk3 = literal_thickets
See previous comment about use of underscores here

2024-07-22 02:40 UTC, ilumsden commented on thicket/thicket.py
> +            raise ValueError(f'Node with name "{name}" not found.')
I would raise a `KeyError` here instead.

2024-07-22 02:40 UTC, ilumsden commented on thicket/thicket.py
> +            warnings.warn(f'More than one node with name "{name}". Returning a list')
I don't think this warning is necessary as long as we document the return type correctly. Regardless if this warning is kept or removed, the docstring needs to be updated to indicate that it can return either `Node` or `List[Node]`.

2024-07-22 21:48 UTC, michaelmckinsey1 commented on thicket/tests/test_add_root_node.py
> +    tk, tk2, tk3 = literal_thickets
53f8718

2024-07-22 21:48 UTC, michaelmckinsey1 commented on thicket/tests/test_get_node.py
> +    tk, tk2, tk3 = literal_thickets
53f8718

2024-07-22 21:54 UTC, michaelmckinsey1 commented on thicket/thicket.py
> +            raise ValueError(f'Node with name "{name}" not found.')
53f8718

2024-07-22 22:01 UTC, michaelmckinsey1 commented on thicket/thicket.py
> +            warnings.warn(f'More than one node with name "{name}". Returning a list')
fcc266a

2024-07-28 04:22 UTC, ilumsden approved these changes
LGTM.

@pearce8 this is ready for your review

2024-07-29 16:58 UTC, pearce8 approved these changes

2024-07-29 16:58 UTC, merged