Fix Bug in add_ncu
LLNL/thicket pull request #196
Opened 2024-07-17 20:40 UTC by michaelmckinsey1

#178 Introduced a bug when `chosen_metrics` was not provided. When `chosen_metrics=None` all ncu metrics are added to the perf dataframe. This PR fixes the bug by modifying the check and moving it, where we can check for duplicate columns when `chosen_metrics=None` aswell.

2024-07-22 02:48 UTC, ilumsden requested changes
The revised logic for `dupe_cols` looks good, but there's a pretty major issue in handling `chosen_metrics` that could easily break `NCUReader` if not addressed.

2024-07-22 02:48 UTC, ilumsden commented on thicket/thicket.py
>              ncu_df = ncu_df[chosen_metrics]
You need to have a type check before doing this. Since you don't validate the type of `chosen_metrics` anywhere, you could get an input that would cause various parts of the rest of the code to error. Off the top of my head, some scenarios are:
* Passing a number (e.g., `int`, `float`) would cause this line to fail with a `KeyError` iff there is not a column with an integer or float index
* Passing a string would cause this line to succeed, but it would also return a `Series` instead of a `DataFrame`. This would cause all the code following this line to fail.

2024-07-22 22:13 UTC, michaelmckinsey1 commented on thicket/thicket.py
>              ncu_df = ncu_df[chosen_metrics]
[b7cc225](https://github.com/LLNL/thicket/pull/196/commits/b7cc2252b7ce94527c483ac59697607d7ec713e1)

2024-08-12 14:09 UTC, ilumsden approved these changes
LGTM.

@pearce8 this PR is ready for your review

2024-10-25 13:31 UTC, slabasan commented
@michaelmckinsey1 Can you please resolve conflicts on this PR? Apologies if I merged these in the wrong order.

2024-10-28 16:26 UTC, slabasan approved these changes

2024-10-28 16:28 UTC, merged