Fix ncu rajacuda
LLNL/thicket pull request #201
Opened 2024-07-29 22:51 UTC by michaelmckinsey1

2024-08-12 14:11 UTC, ilumsden commented
Changing this PR to "work in progress" because there are complications due to mismatches in demangled kernel names from Caliper and NCU.

2024-08-26 16:44 UTC, michaelmckinsey1 commented
See https://github.com/LLNL/thicket/tree/rajaperf-paper

2024-10-04 19:52 UTC, michaelmckinsey1 commented
> Changing this PR to "work in progress" because there are complications due to mismatches in demangled kernel names from Caliper and NCU.

Addressed in new changes.

2024-10-07 19:10 UTC, dyokelson requested changes
Please add a pytest test for each of the cases in your table so we can make sure each is supported (Base_CUDA, Lambda_CUDA, RAJA_CUDA X rajaperf, cub, multiple

2024-10-07 19:10 UTC, dyokelson commented on thicket/ncu.py
> +                        if "cub" in demangled_kernel_name:
Didn't we decide to try to remove the direct string matching and change to if multiple kernels are returned?

2024-10-07 19:10 UTC, dyokelson commented on thicket/ncu.py
> +                        kernel_pattern = rf"{call_trace_str}::(\w+)[<:]"
This feels fragile...and that things could change on us and break this, maybe we can think through other options for matching here.

2024-10-09 16:17 UTC, michaelmckinsey1 commented on thicket/ncu.py
> +                        if "cub" in demangled_kernel_name:
Even for single kernels, the cub kernels have `cub` in the name instead of the call trace. If we wait until there are multiple kernels returned, we would still have to check for `cub` with this logic.

2024-10-09 16:25 UTC, michaelmckinsey1 commented on thicket/ncu.py
> +                        kernel_pattern = rf"{call_trace_str}::(\w+)[<:]"
The regex is only used to match a node or nodes in a subset of the tree, so typically a few nodes. They are not in the same order in the NCU report and in the call tree so we can not match based on ordering. Even more ambitious is the sequence matching for the function signatures of the cub kernels. Since all we have to use to match are the call traces (which are solid using query) and the demangled names (regex part), we have to parse the names in many cases.

2024-10-23 22:15 UTC, michaelmckinsey1 commented on thicket/ncu.py
> +                        kernel_pattern = rf"{call_trace_str}::(\w+)[<:]"
Unit testing added in most recent commits [9a9eab0](https://github.com/LLNL/thicket/pull/201/commits/9a9eab01cfc5b7487e1cebb09906eef02e61308f)

2024-10-25 13:35 UTC, slabasan commented
> This PR supersedes https://github.com/LLNL/thicket/tree/rajaperf-paper branch used for the rajaperf paper.

Do you want to remove the `rajaperf-paper` branch on this repo?

2024-10-25 13:36 UTC, slabasan commented on thicket/ncu.py
> +                        kernel_pattern = rf"{call_trace_str}::(\w+)[<:]"
@dyokelson Can you take one last look at the unit tests to make sure your comments are addressed?

2024-10-25 18:41 UTC, michaelmckinsey1 commented
> > This PR supersedes https://github.com/LLNL/thicket/tree/rajaperf-paper branch used for the rajaperf paper.
> 
> Do you want to remove the `rajaperf-paper` branch on this repo?

Done

2024-10-25 23:46 UTC, dyokelson reviewed
looks good, just the question about disabling tqdm, otherwise will approve

2024-10-25 23:46 UTC, dyokelson commented on thicket/ncu.py
>                  pbar = tqdm(range)
Can they disable tqdm?

2024-10-25 23:47 UTC, dyokelson commented on thicket/ncu.py
> +                        kernel_pattern = rf"{call_trace_str}::(\w+)[<:]"
lgtm

2024-10-28 19:39 UTC, michaelmckinsey1 commented on thicket/ncu.py
>                  pbar = tqdm(range)
Option added in [0ef7c0d](https://github.com/LLNL/thicket/pull/201/commits/0ef7c0d8cfe78abd78230f5569089eecea4ed220)

2024-10-28 21:21 UTC, dyokelson approved these changes
LGTM

2024-10-29 16:44 UTC, slabasan approved these changes

2024-10-29 16:51 UTC, merged