Confidence Interval Stats Function
LLNL/thicket pull request #213
Opened 2024-10-01 18:52 UTC by Yejashi

2024-10-14 16:01 UTC, slabasan commented on README.md
This update seems unrelated to your confidence interval work, should it go into a separate PR?

2024-10-14 16:27 UTC, slabasan commented on thicket/stats/confidence_interval.py
> +            )
Is it necessary to check if the performance table is has two index levels or 1 to set the column name for the confidence interval? Is it appropriate to check if columns is a list of strings or a list of tuples?

2024-10-14 18:33 UTC, slabasan approved these changes

2024-10-15 16:49 UTC, ilumsden requested changes
Mostly looks good. Just a few tweaks that I think should be made. The biggest thing is adding a test case that actually confirms that the computations are correct, at least for a few nodes.

2024-10-15 16:49 UTC, ilumsden commented on README.md
> +documentation, along with tutorials of Thicket in the
I agree with @slabasan's comment. Why is this here?

2024-10-15 16:49 UTC, ilumsden commented on thicket/stats/confidence_interval.py
> +    if columns is None or isinstance(columns, list) is False:
It's more standard to write this if statement this way:
```python
if columns is None or not isinstance(columns, list):
```

2024-10-15 16:49 UTC, ilumsden commented on thicket/stats/confidence_interval.py
> +    if columns is None or isinstance(columns, list) is False:
In fact, `is False` can lead to unintended consequences. You'd probably be fine here, but you really should only use `is False` or `is True` if you are 100% positive that the return type is a boolean. Some functions return a value that implements `__eq__()` instead of a boolean. In that case, this comparison will never work as intended.

2024-10-15 16:49 UTC, ilumsden commented on thicket/stats/confidence_interval.py
> +    if isinstance(confidence_level, (int, float)) is False:
Again, use `not isinstance` instead of `is False`

2024-10-15 16:49 UTC, ilumsden commented on thicket/stats/confidence_interval.py
> +    if confidence_level >= 1 or confidence_level <= 0:
Are values of 1 and 0 actually invalid for confidence intervals? I agree with checking for greater than and less than, but I want to make sure we're not excluding valid values here with the "equals" bit.

2024-10-15 16:49 UTC, ilumsden commented on thicket/stats/confidence_interval.py
> +    z = stats.norm.ppf((1 + confidence_level) / 2)
This doesn't particularly matter, but it would be nice to change `stats` here to something else. Since we refer to `th.stats` quite a bit, just having `stats` might get confusing.

In fact, if this is the only place you're calling into SciPy, just use `import scipy.stats` and change this line to:
```python
z = scipy.stats.norm.ppf(...)
```

2024-10-15 16:49 UTC, ilumsden commented on thicket/stats/confidence_interval.py
> +    for node in thicket.graph.traverse():
It would probably be faster to iterate using the DataFrame than the Graph here. You should be able to do the same with the following for statement:
```python
for node in thicket.dataframe.index.get_level_values(0).unique():
```

If the iteration screws up with that, you can just add `.tolist()` to the end of all of that.

2024-10-15 16:49 UTC, ilumsden commented on thicket/stats/confidence_interval.py
> +            )
`columns` should always behave like a list of tuples.

2024-10-15 16:49 UTC, ilumsden commented on thicket/stats/confidence_interval.py
> +    thicket.statsframe.dataframe = thicket.statsframe.dataframe.sort_index(axis=1)
@slabasan do we want the stats functions to be sorting the columns of the statsframe? Personally, I like this, but I'd like to hear your opinion.

2024-10-15 16:49 UTC, ilumsden commented on thicket/tests/test_stats.py
> +        th.stats.confidence_interval(combined_th, columns=columns, confidence_level=95)
You should have a test here that actually confirms that the result of the computation is what you expect, at least for a few nodes.

2024-10-16 13:56 UTC, Yejashi commented on thicket/stats/confidence_interval.py
> +    if confidence_level >= 1 or confidence_level <= 0:
@ilumsden , I think it's useful to have this check.

Confidence intervals are typically set at levels like 90%, 95%, or 99%, which provide a balance between precision and certainty.

Suppose that the confidence level was 100% or 0%:
  * 100%: This would mean that you are certain the true population parameter is within the interval for every possible sample.  To achieve this, the interval would need to be infinitely wide, making it  uninformative because it doesn't give any meaningful estimate of the range in which the true parameter lies.
  * 0%:  This means you have no confidence that the interval contains the true population parameter.  The interval would shrink to a single point.

2024-10-16 15:43 UTC, ilumsden commented on thicket/stats/confidence_interval.py
> +    if confidence_level >= 1 or confidence_level <= 0:
I get that 1 and 0 aren't super useful. What I want to know is whether they are mathematically valid values. If they are valid, we shouldn't exclude them, which is what this check is doing.

2024-10-16 15:47 UTC, ilumsden commented on thicket/stats/confidence_interval.py
> +    if not isinstance(confidence_level, (int, float)):
@Yejashi another thing I just thought of:

This check should only be for `float`. Since the range of this value is (0, 1) (inclusivity TBD), all valid values will be floats, not integers.

2024-10-16 16:43 UTC, Yejashi commented on thicket/stats/confidence_interval.py
> +    if confidence_level >= 1 or confidence_level <= 0:
Well it doesn't cause errors but the z-score ends up being infinity if you use a confidence_level of 1 and a 0 if you use a confidence level 0. It is utterly pointless to ever use these parameters in the context of calculating the confidence interval.

I can make it so that they can be accepted as input but again, why?

2024-10-21 18:45 UTC, slabasan commented on thicket/stats/confidence_interval.py
> +    thicket.statsframe.dataframe = thicket.statsframe.dataframe.sort_index(axis=1)
This will sort the columns alphabetically right? I think the preference is not to re-arrange the columns on the user, so that the new one appears as the far right column. I do like when we re-sort the dataframe if we have a multi-index on the columns so that columns end up under the right header.

2024-10-21 19:39 UTC, Yejashi commented on thicket/stats/confidence_interval.py
> +    thicket.statsframe.dataframe = thicket.statsframe.dataframe.sort_index(axis=1)
@slabasan  Consider this issue #215 . I was always under the impression that we sort the statsframe dataframe for every statsframe function as a matter of principle, but i've become aware that is not the case. It seems Treecs added in this phenomenon over a year ago for all the statsframe operations.

Personally, i think sorting the statsframe dataframe has great utility. It avoids the annoyance of having to scroll back in for an item under the same index but on opposite ends of the dataframe. However, if this is not something we want to force upon the user, then i would at least like/recommend a new function for sorting the statsframe dataframe.

2024-10-21 19:44 UTC, slabasan commented on thicket/stats/confidence_interval.py
> +    thicket.statsframe.dataframe = thicket.statsframe.dataframe.sort_index(axis=1)
For the confidence interval, is there an option to have a "confidence interval" index on the columns with columns underneath? From what I recall, the confidence interval was being added as a column per column and interval.

Yes agree, if we having the column indices appear at both ends of the statsframe, we should sort by default so the statsframe has 1 instance of the column index. But if we have no column index levels, I'm still reluctant to move things on the user.

2024-10-25 12:55 UTC, slabasan commented on thicket/stats/confidence_interval.py
> +    thicket.statsframe.dataframe = thicket.statsframe.dataframe.sort_index(axis=1)
For now, we will sort the columns as part of the confidence interval API to be consistent with other statsframe functions. We will have a discussion about how we want to handle this going forward.

2024-10-25 12:55 UTC, slabasan approved these changes

2024-10-25 13:15 UTC, merged