Unicode Histogram in Tree
LLNL/thicket pull request #225
Opened 2024-11-12 01:19 UTC by michaelmckinsey1

2024-11-15 22:42 UTC, michaelmckinsey1 commented
Should this be on or off by default?

2025-07-01 15:45 UTC, slabasan requested changes

2025-07-01 15:45 UTC, slabasan commented on thicket/thicket.py
> +            histogram (bool, optional): Whether to show a histogram next to each node of the data for all profiles. Defaults to True.
Looks like the default value is False, can we update these to match? Whether true or false by default?

2025-07-03 19:56 UTC, slabasan approved these changes

2025-07-03 19:57 UTC, merged