Initial push for updated visualization functions
LLNL/thicket pull request #28
Opened 2023-05-25 17:11 UTC by Treece-Burgess

There are three visualization functions that have been pushed up for this PR:

- `display_boxplot`
- `display_heatmap`
- `display_historgram`

Each of the above listed visualization functions have now added the ability to work with a single indexed thicket or a multi indexed thicket (columnar_join).

2023-05-30 15:43 UTC, slabasan commented on thicket/stats/display_boxplot.py
> +from ..utils import verify_thicket_structures
New line between pandas and seaborn imports and utils import (separate third party from local imports per pep8)

2023-05-30 15:53 UTC, slabasan requested changes
One other question, how many datasets have you tested with this vis functionality? Is this code robust against the different datasets we have?

2023-05-30 15:53 UTC, slabasan commented on thicket/stats/display_boxplot.py
> +    """Display a boxplot for each user passed node(s) and column(s). The passed nodes and columns must be from the performance data table.
Can you double check the character width of your docstring? We're trying to keep them to 88 chars.

2023-05-30 15:53 UTC, slabasan commented on thicket/stats/display_boxplot.py
> +        column (list) : List of hardware/timing metrics to view on the y-axis.
Remove space before : in docstrings

2023-05-30 15:53 UTC, slabasan commented on thicket/stats/display_boxplot.py
> +
Remove new line

2023-05-30 15:53 UTC, slabasan commented on thicket/stats/display_boxplot.py
> +        for element in columns[1 : len(columns)]:
Let's remove spaces so it reads `[1 : len(columns)]`. I think this will still pass formatting checks.

2023-05-30 15:53 UTC, slabasan commented on thicket/stats/display_boxplot.py
> +                    "The columns argument must have the same column index throughout for a columnar joined thicket."
This is the error you're displaying if the user passes 2 or more columns that are specified as a tuple, where the first element in the tuple is not the same, correct? Trying to think of a way to simplify this helper error message to limit how many times we say column in the same sentence.

2023-05-30 15:53 UTC, slabasan commented on thicket/stats/display_boxplot.py
> +        filtered_df = df.loc[position].rename(
Why do we need to rename columns here? When you're calling the boxplot functions, can you pass the original column names to the x= parameter?

2023-05-30 15:53 UTC, slabasan commented on thicket/stats/display_histogram.py
> +    """Display a histogram for a user passed node and column. Node and column must come from the performance data table.
Check width of chars in docstring.

2023-05-30 15:53 UTC, slabasan commented on thicket/stats/display_histogram.py
> +
Remove new line

2023-05-30 15:53 UTC, slabasan commented on thicket/stats/display_boxplot.py
Should we add a check to make sure the list of nodes is of node type?

2023-05-30 18:10 UTC, Treece-Burgess commented on thicket/stats/display_boxplot.py
> +                    "The columns argument must have the same column index throughout for a columnar joined thicket."
Yes, that is correct. Possibly could use: Columns must have same index for a passed in columnar_joined thicket. If they are confused, they can run `help()` on the function they are using. Upon running `help()` they should be able to see the python doc string which displays the format needed if a user passes in a columnar_joined thicket.

2023-05-30 18:12 UTC, Treece-Burgess commented on thicket/stats/display_boxplot.py
> +        for element in columns[1 : len(columns)]:
You are wanting to remove the spaces from: `[1 : len(columns)]`? So it would look like the following: 
`[1 : len(columns)]`. Only issue with that could be that flake or black complains about it. The reason I have the spaces there in the first place is due to the formatting checks I ran the other day.

2023-05-30 18:17 UTC, Treece-Burgess commented on thicket/stats/display_boxplot.py
> +        filtered_df = df.loc[position].rename(
Originally we output the hatchet node id (the dictionary) onto the x-axis, after a demo it was decided that instead of using the dictionary node id, we just output the name instead since it would not take up as much space. Without renaming the name column, the x-axis label would end up being `name` instead of `node`. Which is why I rename the columns here.

2023-05-30 18:40 UTC, Treece-Burgess commented on thicket/stats/display_boxplot.py
> +from ..utils import verify_thicket_structures
Next push up will have the space between third party imports and local imports. I am going to go ahead and resolve this comment.

2023-05-30 18:42 UTC, Treece-Burgess commented on thicket/stats/display_boxplot.py
> +    """Display a boxplot for each user passed node(s) and column(s). The passed nodes and columns must be from the performance data table.
I have double checked the sentence width with the python doc strings, and formatted such that we keep them to 88 chars. This will be shown in the next push up. Going to resolve this comment now.

2023-05-30 18:43 UTC, Treece-Burgess commented on thicket/stats/display_boxplot.py
> +        column (list) : List of hardware/timing metrics to view on the y-axis.
Removed space before `:` in docstring for `display_boxplot.py`. This will be seen within the next push up. Going to go ahead and resolve conversation.

2023-05-30 18:44 UTC, Treece-Burgess commented on thicket/stats/display_boxplot.py
> +
Removed new line at line 56 within `display_boxplot.py`. This will be seen in the next push up. Going to go ahead and resolve conversation.

2023-05-30 20:11 UTC, Treece-Burgess commented on thicket/stats/display_boxplot.py
> +        for element in columns[1 : len(columns)]:
Black does complain if you remove the spaces, but I have gone ahead ahead and pushed it up to see if it passes the checks.

2023-05-30 20:18 UTC, Treece-Burgess commented on thicket/stats/display_boxplot.py
I have added checks in `display_histogram.py` and `display_boxplot.py`.

2023-05-30 20:20 UTC, Treece-Burgess commented on thicket/stats/display_boxplot.py
@slabasan I have added node check here and it will be the same for `display_boxplot`. Llet me know if this looks fine or if you had envisioned something else.

2023-05-31 16:02 UTC, Treece-Burgess commented on thicket/stats/display_boxplot.py
> +        filtered_df = df.loc[position].rename(
Seaborn uses the column header as the main x-axis label. As discussed previously we wanted to use the name column as the tick marker labels instead of the hatchet node dictionary. Therefore, if we pass `name` to perform the following code snippet: `sns.boxplot(data=filtered_df, x="name", y=" ", **kwargs)` we would end up having the main x-axis label as `name` due to how Seaborn works. 

Due to this I rename the `name` column to be `node` such that we get the shortened name, but users also will know it is a node.

2023-05-31 21:37 UTC, slabasan commented on thicket/stats/display_boxplot.py
> +        filtered_df = df.loc[position].rename(
See updated code, I've added a statement to indicate the need for the renaming. Let me know what you think.

2023-05-31 21:58 UTC, Treece-Burgess commented on thicket/stats/display_boxplot.py
> +        filtered_df = df.loc[position].rename(
I believe that `name` and `node` need to be swapped within this sentence: _rename columns such that the x-axis label is "name" and not "node"_.

So it would read: _rename columns such that the x-axis label is "node" and not "name"_. If we didn't rename here then the x-axis label would end up being `name`.

2023-06-02 17:49 UTC, slabasan approved these changes

2023-06-02 17:49 UTC, slabasan commented on thicket/stats/display_boxplot.py
> +        filtered_df = df.loc[position].rename(
Nice catch, made this change.

2023-06-02 17:59 UTC, merged