Update to aggregated statistical functions
LLNL/thicket pull request #29
Opened 2023-05-25 17:45 UTC by Treece-Burgess

This PR has two primary goals, one to split previous aggregated statistical functions which had two statistical operations into individual functions with a single statistical operation, and the second is to add the functionality to work with multi-indexed thickets (columnar-join). Below will be a list of previous functions that contained two statistical operations and that are now split into individual functions: 

- `calc_extremum.py`
    - Split into: `minimum.py` and `maximum.py`
- `calc_deviation.py`
    - Split into: `std.py` and `variance.py`
- `calc_average.py`
    - Split into: `mean.py` and `median.py`

2023-05-30 16:28 UTC, slabasan requested changes

2023-05-30 16:28 UTC, slabasan commented on thicket/stats/calc_boxplot_statistics.py
> +    if thicket.dataframe.columns.nlevels == 1:
Add a comment above if block to indicate this code parses performance data with no columnar index

2023-05-30 16:28 UTC, slabasan commented on thicket/stats/calc_boxplot_statistics.py
> +
Remove new line, add a comment above else block to indicate this code parses columnar joined performance data

2023-05-30 16:28 UTC, slabasan commented on thicket/stats/check_normality.py
Separate imports with a new line, scipy separate from local ..utils import

2023-05-30 16:28 UTC, slabasan commented on thicket/stats/check_normality.py
> +
remove newline

2023-05-30 16:28 UTC, slabasan commented on thicket/stats/correlation_nodewise.py
> +from ..utils import verify_thicket_structures
new line between scipy and utils

2023-05-30 16:28 UTC, slabasan commented on thicket/stats/correlation_nodewise.py
> +                       passed in with the format:(column index,column name).
space after colon and after comma

2023-05-30 16:28 UTC, slabasan commented on thicket/stats/correlation_nodewise.py
> +                       passed in with the format:(column index,column name).
space after colon and after comma

2023-05-30 16:28 UTC, slabasan commented on thicket/stats/correlation_nodewise.py
> +        raise ValueError("To see a list of valid columns run get_perf_columns().")
Update to `raise ValueError("To see a list of valid columns, please run Thicket.get_perf_columns().")`

2023-05-30 16:28 UTC, slabasan commented on thicket/stats/maximum.py
> +from ..utils import verify_thicket_structures
New line between imports

2023-05-30 16:28 UTC, slabasan commented on thicket/stats/maximum.py
Should this file be called calc_maximum to match your other files?

2023-05-30 16:28 UTC, slabasan commented on thicket/stats/maximum.py
> +                        passed in with the format:(column index,column name).
Space after colon and after comma

2023-05-30 16:28 UTC, slabasan commented on thicket/stats/mean.py
Same question as above about the filename.

2023-05-30 16:28 UTC, slabasan commented on thicket/stats/mean.py
> +import pandas as pd
Separate imports by third party (numpy and pandas) by local imports (..utils)

2023-05-30 16:28 UTC, slabasan commented on thicket/stats/mean.py
> +    Designed to take in a thicket, and append one or more columns to the aggregated statistics table for
Check char width here

2023-05-30 16:28 UTC, slabasan commented on thicket/stats/maximum.py
> +        raise ValueError("To see a list of valid columns run get_perf_columns().")
Update to raise ValueError("To see a list of valid columns, please run Thicket.get_perf_columns().")

2023-05-30 16:28 UTC, slabasan commented on thicket/stats/check_normality.py
>          raise ValueError("To see a list of valid columns run get_perf_columns().")
Update to raise ValueError("To see a list of valid columns, please run Thicket.get_perf_columns().")

2023-05-30 16:28 UTC, slabasan commented on thicket/stats/mean.py
> +        raise ValueError("To see a list of valid columns run get_perf_columns().")
Update to raise ValueError("To see a list of valid columns, please run Thicket.get_perf_columns().")

2023-05-30 16:28 UTC, slabasan commented on thicket/stats/mean.py
> +
remove new line

2023-05-30 16:28 UTC, slabasan commented on thicket/stats/median.py
> +from ..utils import verify_thicket_structures
Separate imports

2023-05-31 15:10 UTC, Treece-Burgess commented on thicket/stats/maximum.py
The only function that I left with the `calc_` naming scheme was `calc_boxplot_statistics` due to it possibly confusing a user if I removed the `calc` portion. The other functions I removed the `calc` portion.  I did this to be more in line with numpy and pandas. For example if we want to do the mean calculation in numpy it would be `np.mean()` so I went with a similar approach for our functions that are now broken apart. So now a user could do the following `import thicket as th` -> `th.mean()`. We have talked about keeping similarities with other libraries, which I have went with here, but if we want to be more distinct here, I can add the `calc` back.

2023-05-31 15:11 UTC, Treece-Burgess commented on thicket/stats/mean.py
See comment on this issue here: https://github.com/LLNL/thicket/pull/29#discussion_r1211877070.

2023-05-31 15:25 UTC, Treece-Burgess commented on thicket/stats/mean.py
> +    Designed to take in a thicket, and append one or more columns to the aggregated statistics table for
I have checked the char width for all files within this PR and re-formatted all doc strings accordingly with us wanting the char width to be 88.

2023-05-31 23:09 UTC, slabasan approved these changes

2023-05-31 23:09 UTC, merged