Rename add_column_from_metadata_to_ensemble function
LLNL/thicket pull request #97
Opened 2023-10-04 20:46 UTC by MichaelMcKinsey1

Rename `add_column_from_metadata_to_ensemble` to `metadata_column_to_perfdata`. Current name is too long and uses `ensemble` which is terminology we have moved away from.

2023-10-09 23:12 UTC, slabasan requested changes

2023-10-09 23:12 UTC, slabasan commented on docs/thicket_rajaperf_clustering.ipynb
This file should be left unchanged. Changes to the notebooks should first go to thicket-tutorial.

2023-10-10 02:16 UTC, MichaelMcKinsey1 commented on docs/thicket_rajaperf_clustering.ipynb
made pr over there https://github.com/LLNL/thicket-tutorial/pull/24

2023-10-31 05:06 UTC, slabasan approved these changes

2023-10-31 05:06 UTC, merged